"use client";

import {useRouter} from "next/navigation";
import {Icon} from "@/components/host-landing/icons";
import type {OwnerBooking} from "@/lib/owner-bookings";
import {calendarMetrics,type PropertyCalendar} from "@/lib/owner-calendar";

const paths=["M2 42 C18 51,25 31,38 36 S55 52,67 22 S84 39,99 14 S119 19,128 12","M2 45 C20 35,31 40,44 43 S61 16,72 25 S86 0,99 18","M2 43 C18 36,26 15,41 25 S55 40,69 25 S86 35,104 17","M2 45 C17 32,25 20,39 28 S56 40,69 21 S84 3,98 18"];
export function AnalyticsRow({id,property,bookings}:{id:string;property:PropertyCalendar;bookings:OwnerBooking[]}){const metrics=calendarMetrics(property),confirmed=bookings.filter(x=>x.status==="Confirmed"),pending=bookings.filter(x=>x.status==="Pending");return <div className="grid grid-cols-[.78fr_.78fr_.98fr_.78fr_1.05fr_1.05fr_1.38fr] gap-[10px] max-[1100px]:grid-cols-2 max-[600px]:grid-cols-1"><Metric title="Occupancy rate" value={`${Math.max(0,76-metrics.blocked)}%`} change="12% vs Apr" path={paths[0]}/><Metric title="Nights booked" value={String(confirmed.length*3)} change="3 vs Apr" path={paths[1]}/><Metric title="Average nightly rate" value={`EGP ${metrics.average.toLocaleString()}`} change="EGP 120 vs Apr" path={paths[2]}/><Metric title="Upcoming check-ins" value={String(confirmed.length)} note={confirmed[0]?`Next: ${confirmed[0].dates.split("-")[0]}`:"None"} path={paths[3]}/><Blocked id={id} property={property}/><Pending bookings={pending}/><Housekeeping property={property}/></div>}
function Shell({children,onClick}:{children:React.ReactNode;onClick?:()=>void}){return <section onClick={onClick} tabIndex={onClick?0:undefined} onKeyDown={e=>{if(onClick&&(e.key==="Enter"||e.key===" ")){e.preventDefault();onClick()}}} className={`h-[154px] overflow-hidden rounded-[8px] border border-[#e4e8ef] bg-white p-[12px] shadow-[0_3px_12px_rgba(31,38,72,.025)] transition-shadow hover:shadow-[var(--shadow-sm)] ${onClick?"cursor-pointer focus-visible:outline-2 focus-visible:outline-[var(--brand)]":""}`}>{children}</section>}
function Metric({title,value,change,note,path}:{title:string;value:string;change?:string;note?:string;path:string}){return <Shell><b className="owner-label">{title}</b><strong className="owner-label mt-[10px] block whitespace-nowrap">{value}</strong><p className="owner-body mt-2">{change??note}</p><svg aria-hidden="true" className="mt-2 h-[62px] w-full" preserveAspectRatio="none" viewBox="0 0 130 54"><path d={path} fill="none" stroke="#8b68ef" strokeWidth="2"/></svg></Shell>}
function Header({title,action,onClick}:{title:string;action:string;onClick:()=>void}){return <div className="flex items-center justify-between"><b className="owner-label">{title}</b><button onClick={e=>{e.stopPropagation();onClick()}} className="rounded p-1 hover:bg-[#f5f0ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]">{action}</button></div>}
function Blocked({id,property}:{id:string;property:PropertyCalendar}){const router=useRouter(),rows=Object.entries(property.dates).filter(([,x])=>x.state==="blocked"||x.state==="unavailable").slice(0,3);return <Shell onClick={()=>router.push(`/owner/properties/${id}/availability-rules`)}><Header title="Blocked dates" action="Add" onClick={()=>router.push(`/owner/properties/${id}/calendar-management`)}/><div className="mt-2">{rows.length?rows.map(([date,item])=><div key={date} className="owner-body flex h-[30px] items-center border-b"><i className="mr-2 size-[7px] rounded-full bg-[#959ba5]"/><b>{date}</b><span className="ml-auto">{item.reason??"Owner blocked"}</span></div>):<p className="owner-body mt-3">No blocked dates</p>}</div></Shell>}
function Pending({bookings}:{bookings:OwnerBooking[]}){const router=useRouter();return <Shell onClick={()=>router.push("/owner/bookings")}><Header title="Pending requests" action="View all" onClick={()=>router.push("/owner/bookings")}/><div className="mt-2">{bookings.slice(0,3).map(x=><div key={x.id} className="owner-body border-b py-1"><b className="block">{x.dates}</b><small>{x.guest}</small></div>)}</div></Shell>}
function Housekeeping({property}:{property:PropertyCalendar}){return <Shell><Header title="Housekeeping & turnover" action="View all" onClick={()=>alert(property.housekeeping.map(x=>`${x.date}: ${x.task}`).join("\n")||"No housekeeping tasks")}/><div className="mt-2">{property.housekeeping.slice(0,3).map(x=><div key={x.id} className="owner-body flex h-[34px] items-center border-b"><Icon name="gear" className="mr-2 size-3"/><b>{x.date.slice(5)}</b><span className="ml-auto">{x.task}</span></div>)}</div></Shell>}
