import {Icon} from "@/components/host-landing/icons";

const chartPaths=["M2 42 C18 51,25 31,38 36 S55 52,67 22 S84 39,99 14 S119 19,128 12","M2 45 C20 35,31 40,44 43 S61 16,72 25 S86 0,99 18 L99 52 L2 52Z","M2 43 C18 36,26 15,41 25 S55 40,69 25 S86 35,104 17 S116 15,128 20","M2 45 C17 32,25 20,39 28 S56 40,69 21 S84 3,98 18 S113 7,128 14"];

export function AnalyticsRow(){return <div className="grid grid-cols-[.78fr_.78fr_.98fr_.78fr_1.05fr_1.05fr_1.38fr] gap-[10px] max-[1100px]:grid-cols-2 max-[600px]:grid-cols-1"><Metric title="Occupancy rate" value="76%" change="12% vs Apr" path={chartPaths[0]}/><Metric title="Nights booked" value="18" change="3 vs Apr" path={chartPaths[1]}/><Metric title="Average nightly rate" value="EGP 1,320" change="EGP 120 vs Apr" path={chartPaths[2]}/><Metric title="Upcoming check-ins" value="3" note="Next: May 20" path={chartPaths[3]}/><Blocked/><Pending/><Housekeeping/></div>}
function Shell({children}:{children:React.ReactNode}){return <section className="h-[154px] overflow-hidden rounded-[8px] border border-[#e4e8ef] bg-white p-[12px] shadow-[0_3px_12px_rgba(31,38,72,.025)]">{children}</section>}
function Metric({title,value,change,note,path}:{title:string;value:string;change?:string;note?:string;path:string}){return <Shell><b className="owner-label">{title}</b><strong className="owner-label mt-[10px] block whitespace-nowrap">{value}</strong>{change?<p className="owner-body mt-[8px] flex items-center gap-[4px]"><Icon name="arrow-up" className="size-[12px]"/><b className="owner-label">{change.split(" vs")[0]}</b><span className="owner-body">{change.includes(" vs")?`vs${change.split(" vs")[1]}`:""}</span></p>:<p className="owner-body mt-[8px]">{note}</p>}<Spark path={path}/></Shell>}
function Spark({path}:{path:string}){return <svg aria-hidden="true" className="mt-[8px] h-[62px] w-full" preserveAspectRatio="none" viewBox="0 0 130 54"><defs><linearGradient id="sparkFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#8b68ef" stopOpacity=".2"/><stop offset="1" stopColor="#8b68ef" stopOpacity=".02"/></linearGradient></defs><path d={`${path} L128 54 L2 54 Z`} fill="url(#sparkFill)" stroke="none"/><path d={path} fill="none" stroke="#8b68ef" strokeLinecap="round" strokeWidth="2"/></svg>}
function Header({title,action}:{title:string;action:string}){return <div className="flex items-center justify-between"><b className="owner-label">{title}</b><button className="owner-button-text">{action}</button></div>}
function Blocked(){const rows=[["May 31, 2026","Owner blocked"],["Jun 15 – Jun 17, 2026","Personal use"],["Jul 04 – Jul 06, 2026","Maintenance"]];return <Shell><Header title="Blocked dates" action="Add"/><div className="mt-[7px]">{rows.map(([date,reason])=><div key={date} className="owner-body flex h-[30px] items-center border-b border-[#edf0f5] last:border-0"><i className="mr-[7px] size-[7px] shrink-0 rounded-full bg-[#959ba5]"/><b>{date}</b><span className="owner-body ml-auto text-right">{reason}</span></div>)}</div><button className="owner-button-text mt-[4px] block w-full text-center">View all</button></Shell>}
function Pending(){const rows=[["May 27 – May 29","Sara Ali"],["Jun 10 – Jun 12","Mohamed Adel"],["Jun 18 – Jun 19","Yara Hossam"]];return <Shell><Header title="Pending requests" action="View all"/><div className="mt-[7px]">{rows.map(([date,name])=><div key={date} className="owner-body flex min-h-[34px] items-start border-b border-[#edf0f5] py-[5px] last:border-0"><i className="mr-[7px] mt-[2px] size-[7px] shrink-0 rounded-full bg-[#ffa21a]"/><span><b className="owner-label block">{date}</b><small className="owner-helper mt-[2px] block">{name}</small></span></div>)}</div></Shell>}
function Housekeeping(){const rows=[["May 20","Clean before 2 PM"],["May 25","Inspection needed"],["May 29","Laundry pickup"]];return <Shell><Header title="Housekeeping & turnover" action="View all"/><div className="mt-[7px]">{rows.map(([date,task])=><div key={date} className="owner-body flex h-[34px] items-center border-b border-[#edf0f5] last:border-0"><span className="owner-badge mr-[8px] grid size-[16px] shrink-0 place-items-center rounded-full bg-[#f0eaff]"><Icon name="gear" className="size-[9px]"/></span><b>{date}</b><span className="owner-body ml-auto text-right">{task}</span></div>)}</div></Shell>}
