"use client";

import Image from "next/image";
import Link from "next/link";
import {useSearchParams} from "next/navigation";
import {useEffect,useMemo,useState} from "react";
import {Icon} from "@/components/host-landing/icons";
import {DarLogo} from "@/components/brand/dar-logo";
import {BulkActions,DashboardLower,Notes} from "./dashboard-extras";
import {ReferenceCalendar} from "./reference-calendar";
import {ReferenceBookingPanel} from "./property-summary-panel";

type DayState="available"|"booked"|"blocked";
type SavedState=Record<string,DayState>;
const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
const weekdays=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"];

export default function CalendarManagementPage({id}:{id:string}){
  const search=useSearchParams();
  const [cursor,setCursor]=useState(new Date(2026,4,1));
  const [saved,setSaved]=useState<SavedState>(()=>{if(typeof window==="undefined")return {};try{return JSON.parse(localStorage.getItem(`dar-owner-calendar:${id}`)??"{}")}catch{return {}}});
  const [selected,setSelected]=useState<string[]>([]);
  useEffect(()=>{localStorage.setItem(`dar-owner-calendar:${id}`,JSON.stringify(saved))},[saved,id]);
  const back=search.get("from")==="rules"?`/owner/properties/${id}/availability-rules`:"/owner/properties";
  const select=(key:string)=>setSelected(current=>current.includes(key)?current.filter(x=>x!==key):current.length===1?[current[0],key].sort():[key]);
  const update=(state:DayState)=>setSaved(current=>{const next={...current};selected.forEach(key=>{if(current[key]!=="booked")next[key]=state});return next});
  const changeMonth=(delta:number)=>setCursor(current=>new Date(current.getFullYear(),current.getMonth()+delta,1));
  return <main className="min-h-screen bg-[#f7f8fb] text-[#11183b]"><div className="owner-dashboard-frame"><Sidebar id={id}/><section className="owner-dashboard-main"><Header/><div className="owner-dashboard-content"><div className="flex items-start justify-between gap-4 max-[760px]:block"><div><h1 className="owner-page-title">Calendar management</h1><p className="owner-page-description mt-[5px]">Manage availability, pricing, blocked dates and booking requests across your listings.</p></div><ActionButtons/></div><Filters/><div className="mt-5 grid grid-cols-[minmax(0,1fr)_340px] gap-4 max-[1000px]:grid-cols-1"><ReferenceCalendar cursor={cursor} saved={saved} selected={selected} onSelect={select} onMove={changeMonth}/><ReferenceBookingPanel/></div><DashboardLower/><Notes/><BulkActions selected={selected} onUpdate={update}/><Link href={back} className="owner-body mt-4 inline-flex items-center gap-2"><Icon name="arrow-left" className="size-[14px]"/>Back</Link></div><MobileNav id={id}/></section></div></main>;
}

function ActionButtons(){return <div className="flex flex-wrap justify-end gap-[8px] max-[760px]:mt-4 max-[760px]:justify-start"><button className="owner-button-text flex h-[34px] items-center gap-2 rounded-[5px] border border-[#dce1eb] px-[13px]"><Icon name="refresh" className="size-[14px]"/>Sync calendar</button><button className="owner-button-text flex h-[34px] items-center gap-2 rounded-[5px] border border-[#dce1eb] px-[13px]"><Icon name="download" className="size-[14px]"/>Export availability</button><button className="owner-button-text flex h-[34px] items-center gap-2 rounded-[5px] bg-[#5824e6] px-[16px] text-white"><Icon name="plus" className="size-[14px]"/>Add blocked dates</button></div>}
function Filters(){const [view,setView]=useState("Month");const [display,setDisplay]=useState("Calendar");return <section className="mt-[16px] grid grid-cols-[1.15fr_.75fr_1fr] gap-[14px] rounded-[8px] border border-[#e6e9f1] bg-white p-[12px] max-[850px]:grid-cols-1"><div><b className="owner-label">Property</b><PropertySelector/></div><Segment label="View" items={["Month","Week","Day"]} value={view} set={setView}/><Segment label="Display" items={["Calendar","List view","Pricing view"]} value={display} set={setDisplay}/></section>}
function Segment({label,items,value,set}:{label:string;items:string[];value:string;set:(v:string)=>void}){return <div><b className="owner-label">{label}</b><div className="mt-[6px] flex h-[36px] rounded-[6px] border border-[#e1e5ed] p-[3px]">{items.map(item=>item==="Pricing view"?<Link key={item} href="/owner/properties/1/seasonal-pricing" className="owner-button-text flex flex-1 items-center justify-center rounded-[4px]">{item}</Link>:<button key={item} onClick={()=>set(item)} className={`owner-button-text flex-1 rounded-[4px] ${value===item?"border border-[#7040ef] bg-[#f5f0ff] text-[var(--brand)]":"text-[#68718d]"}`}>{item}</button>)}</div></div>}

function Sidebar({id}:{id:string}){const items=[["Dashboard","home","/owner"],["Properties","hotel","/owner/properties"],["Bookings","calendar","/owner/bookings/request-decision"],["Calendar","calendar",`/owner/properties/${id}/calendar`],["Inbox","message","/owner/messages"],["Reviews","star","/owner/reviews"],["Payouts","wallet","/owner/payouts"],["Settings","target","/owner/settings"]];return <aside className="w-[205px] shrink-0 border-r border-[#edf0f6] bg-white px-[15px] pb-[18px] pt-[16px] max-[760px]:hidden"><DarLogo surface="light" alt="DAR Find Your Perfect Stay" width={610} height={260} className="ml-[8px] h-auto w-[105px] object-contain object-left"/><nav className="mt-[22px] space-y-[2px]">{items.map(([label,icon,href])=><Link key={label} href={href} className={`owner-button-text flex h-[38px] items-center gap-[12px] rounded-[7px] px-[9px] ${label==="Calendar"?"bg-[#f5f0ff] text-[var(--brand)]":"text-[#566080]"}`}><Icon name={icon} className="size-[16px]"/>{label}{label==="Inbox"?<b className="owner-label ml-auto grid size-[16px] place-items-center rounded-[4px] bg-[#5824e6] text-white">2</b>:null}</Link>)}</nav><PromoCards/></aside>}
function PromoCards(){return <><div className="owner-body mt-[20px] rounded-[8px] bg-[#f7f3ff] px-[13px] pt-[13px]"><b>List more, earn more</b><p className="owner-body mt-[4px]">Complete your property<br/>and start welcoming guests.</p><button className="owner-button-text mt-[10px] h-[31px] w-full rounded-[5px] border border-[#9c7cff] bg-white">Finish property</button><Image src="/finish-property-illustration.png" alt="" width={132} height={78} className="mx-auto mt-[3px] h-[78px] w-[132px] object-contain"/></div><div className="owner-body mt-[20px] rounded-[8px] bg-[#fbfbfe] p-[13px]"><b>Need help?</b><p className="owner-body mt-[7px]">Our support team is here<br/>24/7 to help you.</p><button className="owner-button-text mt-[10px] flex h-[31px] w-full items-center justify-center gap-[7px] rounded-[5px] border border-[#9c7cff]"><Icon name="headset" className="size-[14px]"/>Contact support</button></div></>}
function Header(){return <><header className="flex h-[58px] items-center justify-end border-b border-[#edf0f6] px-[25px] max-[760px]:hidden"><span className="owner-body relative"><Icon name="bell" className="size-[18px]"/><b className="owner-label absolute -right-2 -top-2 grid size-[14px] place-items-center rounded-full bg-red-500 text-white">3</b></span><Image src="/publish-avatar-ahmed-reference.svg" alt="Ahmed Hassan" width={30} height={30} className="ml-7 size-[30px] rounded-full object-cover"/><b className="owner-label ml-3">Ahmed H.</b><Icon name="chevron" className="ml-3 size-[11px]"/></header><header className="hidden h-[64px] items-center justify-between border-b border-[#edf0f6] px-4 max-[760px]:flex"><Icon name="menu" className="size-5"/><DarLogo surface="light" alt="DAR" width={88} height={36} className="h-[35px] w-[88px] object-contain"/><span className="owner-body relative"><Icon name="bell" className="size-5"/><b className="owner-label absolute -right-2 -top-2 grid size-4 place-items-center rounded-full bg-red-500 text-white">3</b></span></header></>}
function PropertySelector(){return <div className="flex h-[55px] w-[310px] items-center rounded-[7px] border border-[#e0e4ed] px-[9px] max-[760px]:mt-4 max-[760px]:w-full"><Image src="/rejected-property-reference.svg" alt="Modern Apartment in Zamalek" width={56} height={42} className="h-[42px] w-[56px] rounded-[5px] object-cover"/><div className="ml-3 flex-1"><b className="owner-label block">Modern Apartment in Zamalek</b><small className="owner-helper mt-1 block">Zamalek, Cairo, Egypt</small></div><Icon name="chevron" className="size-3"/></div>}

function CalendarCard({cursor,saved,selected,onSelect,onMove,onToday}:{cursor:Date;saved:SavedState;selected:string[];onSelect:(k:string)=>void;onMove:(n:number)=>void;onToday:()=>void}){const cells=useMemo(()=>makeCalendar(cursor),[cursor]);return <section className="overflow-hidden rounded-[9px] border border-[#e6e9f1] bg-white"><div className="flex min-h-[68px] items-center border-b border-[#e8ebf2] px-[16px] max-[560px]:flex-wrap max-[560px]:gap-3 max-[560px]:py-3"><div><h2 className="owner-section-title">{months[cursor.getMonth()]} {cursor.getFullYear()}</h2><p className="owner-body mt-1">Select dates to update availability.</p></div><div className="ml-auto flex items-center gap-[7px] max-[560px]:ml-0 max-[560px]:w-full"><button onClick={onToday} className="owner-button-text h-[32px] rounded-[5px] border border-[#dce1eb] px-[14px]">Today</button><button aria-label="Previous month" onClick={()=>onMove(-1)} className="grid size-[32px] place-items-center rounded-[5px] border border-[#dce1eb]"><Icon name="chevron" className="size-3 rotate-90"/></button><button aria-label="Next month" onClick={()=>onMove(1)} className="grid size-[32px] place-items-center rounded-[5px] border border-[#dce1eb]"><Icon name="chevron" className="size-3 -rotate-90"/></button><button className="owner-button-text ml-[5px] flex h-[32px] items-center gap-2 rounded-[5px] border border-[#dce1eb] px-[12px]"><Icon name="calendar" className="size-[14px]"/>Month<Icon name="chevron" className="size-[10px]"/></button></div></div><div className="grid grid-cols-7 border-b border-[#e8ebf2] bg-[#fafbfe]">{weekdays.map(day=><div key={day} className="owner-body py-[10px] text-center text-[#65708e]">{day}</div>)}</div><div className="grid grid-cols-7">{cells.map(cell=><DayCell key={cell.key} cell={cell} state={saved[cell.key]??cell.state} selected={selected.includes(cell.key)} onSelect={onSelect}/>)}</div><Legend/></section>}
type Cell={key:string;day:number;muted:boolean;state:DayState;price:number};
function makeCalendar(cursor:Date){const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1).getDay();const result:Cell[]=[];for(let i=0;i<42;i++){const d=new Date(y,m,1-first+i),day=d.getDate(),muted=d.getMonth()!==m,key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;let state:DayState="available";if(!muted&&((day>=8&&day<=10)||(day>=22&&day<=24)))state="booked";if(!muted&&(day===5||day===6||day===18))state="blocked";result.push({key,day,muted,state,price:state==="booked"?0:day%6===0?2900:2500})}return result}
function DayCell({cell,state,selected,onSelect}:{cell:Cell;state:DayState;selected:boolean;onSelect:(k:string)=>void}){const today=cell.key==="2025-05-18";return <button disabled={state==="booked"} onClick={()=>onSelect(cell.key)} className={`relative min-h-[86px] border-b border-r border-[#edf0f5] p-[8px] text-left transition-colors max-[760px]:min-h-[67px] max-[760px]:p-[5px] ${cell.muted?"bg-[#fbfcfe] text-[#b4bac8]":"hover:bg-[#faf8ff]"} ${state==="booked"?"cursor-not-allowed bg-[#f0edff]":""} ${state==="blocked"?"bg-[#f7f8fa]":""} ${selected?"z-10 bg-[#f6f1ff] ring-2 ring-inset ring-[#6332ee]":""}`}><span className={`owner-badge grid size-[22px] place-items-center rounded-full ${today?"bg-[#5824e6] text-white":""}`}>{cell.day}</span>{!cell.muted?<><span className={`owner-body mt-[7px] block max-[560px]:hidden ${state==="booked"?"text-[var(--brand)]":state==="blocked"?"text-[#81899d]":"text-[#4f5877]"}`}>{state==="booked"?"Booked":state==="blocked"?"Blocked":`EGP ${cell.price.toLocaleString()}`}</span>{state==="booked"?<i className="absolute bottom-[8px] right-[8px] size-[6px] rounded-full bg-[#6332ee]"/>:null}</>:null}</button>}
function Legend(){return <div className="owner-body flex min-h-[48px] flex-wrap items-center gap-[18px] px-[16px] text-[#596382]">{[["#ffffff","Available"],["#f0edff","Booked"],["#f7f8fa","Blocked"],["#f6f1ff","Selected"]].map(([color,label])=><span className="owner-body flex items-center gap-2" key={label}><i className="size-[12px] rounded-[3px] border border-[#dce1eb]" style={{background:color}}/>{label}</span>)}</div>}
function SidePanel({selected,saved,onUpdate}:{selected:string[];saved:SavedState;onUpdate:(s:DayState)=>void}){const current=selected.length?selected.map(x=>new Date(`${x}T12:00:00`).toLocaleDateString("en-GB",{day:"numeric",month:"short"})).join(" – "):"No dates selected";const isBooked=selected.some(x=>saved[x]==="booked");return <aside className="space-y-[14px]"><section className="rounded-[8px] border border-[#e6e9f1] p-[14px]"><h2 className="owner-section-title">Selected dates</h2><div className="mt-[12px] rounded-[6px] bg-[#f8f5ff] p-[12px]"><b className="owner-label block">{current}</b><small className="owner-helper mt-1 block">{selected.length?`${selected.length} date${selected.length>1?"s":""} selected`:"Choose one date, then another for a range."}</small></div><label className="owner-label mt-[13px] block">Nightly price<div className="owner-body mt-[7px] flex h-[34px] items-center rounded-[5px] border border-[#dce1eb] px-[10px]"><span>EGP</span><input defaultValue="2,500" className="owner-input-text ml-3 min-w-0 flex-1 outline-none"/></div></label><div className="mt-[14px] space-y-[8px]"><button disabled={!selected.length||isBooked} onClick={()=>onUpdate("available")} className="owner-button-text h-[34px] w-full rounded-[5px] border border-[#9d7cff] text-[var(--brand)] disabled:opacity-40">Mark as available</button><button disabled={!selected.length||isBooked} onClick={()=>onUpdate("blocked")} className="owner-button-text h-[34px] w-full rounded-[5px] bg-[#5824e6] text-white disabled:opacity-40">Block selected dates</button></div>{isBooked?<p className="owner-body mt-3">Booked dates are read-only and cannot be changed.</p>:null}</section><section className="rounded-[8px] bg-[#f8f5ff] p-[14px]"><div className="flex items-center gap-2 text-[var(--brand)]"><Icon name="calendar" className="size-[17px]"/><b className="owner-label">Availability rules applied</b></div><p className="owner-body mt-[9px]">Minimum stay and gap-night rules are reflected in this calendar.</p><Link href={`/owner/properties/1/availability-rules`} className="owner-body mt-[10px] block">Edit availability rules <Icon name="arrow-right" className="ml-1 inline size-[13px]"/></Link></section></aside>}
function MobileNav({id}:{id:string}){return <nav className="owner-body fixed inset-x-0 bottom-0 z-30 hidden h-[66px] items-center justify-around border-t border-[#e6e9f1] bg-white max-[760px]:flex"><Link href="/owner" className="owner-body text-center"><Icon name="home" className="mx-auto size-5"/><small>Dashboard</small></Link><Link href="/owner/bookings/request-decision" className="owner-body text-center"><Icon name="calendar" className="mx-auto size-5"/><small>Bookings</small></Link><Link href={`/owner/properties/${id}/edit`} className="owner-button-text grid size-11 place-items-center rounded-full bg-[#5824e6] text-white"><Icon name="plus" className="size-5"/></Link><Link href={`/owner/properties/${id}/calendar`} className="owner-body text-center"><Icon name="calendar" className="mx-auto size-5"/><small>Calendar</small></Link><span className="owner-body text-center"><Icon name="user" className="mx-auto size-5"/><small>Profile</small></span></nav>}
