"use client";

import Link from "next/link";
import {useRouter,useSearchParams} from "next/navigation";
import {useMemo,useRef,useState} from "react";
import {Icon} from "@/components/host-landing/icons";
import {useOwnerBookings} from "@/lib/owner-bookings";
import {useOwnerPropertyDraft} from "@/lib/owner-property-draft";
import {calendarRange,ensurePropertyCalendar,patchOwnerCalendar,patchPropertyCalendar,updateCalendarDates,useOwnerCalendar,type AvailabilityState,type CalendarDisplay,type CalendarView} from "@/lib/owner-calendar";
import {BulkActions,DashboardLower,Notes} from "./dashboard-extras";
import {ReferenceCalendar} from "./reference-calendar";
import {ReferenceBookingPanel} from "./property-summary-panel";

export default function CalendarManagementPage({id}:{id:string}){
  const router=useRouter(),search=useSearchParams(),store=useOwnerCalendar(),bookings=useOwnerBookings(),draft=useOwnerPropertyDraft();
  const property=ensurePropertyCalendar(store,id),[cursor,setCursor]=useState(new Date(2026,4,1)),[anchor,setAnchor]=useState(""),[end,setEnd]=useState(""),[busy,setBusy]=useState(""),[feedback,setFeedback]=useState<{tone:"success"|"error";text:string}|null>(null),fileRef=useRef<HTMLInputElement>(null);
  const selected=useMemo(()=>anchor?calendarRange(anchor,end||anchor):[],[anchor,end]);
  const selectedBooking=useMemo(()=>bookings.find(b=>b.property.toLowerCase().includes(id==="1"?"modern apartment":"studio")&&b.status!=="Cancelled")??bookings.find(b=>b.status!=="Cancelled"),[bookings,id]);
  const propertyOptions=useMemo(()=>[{id:"1",name:draft.title||"Modern Apartment in Zamalek",location:[draft.neighborhood,draft.city].filter(Boolean).join(", ")||"Zamalek, Cairo"},...Array.from(new Set(bookings.map(b=>b.property))).filter(name=>name!==draft.title).map((name,index)=>({id:String(index+2),name,location:"Cairo, Egypt"}))],[bookings,draft]);
  const act=async(name:string,fn:()=>boolean|void)=>{if(busy)return;setBusy(name);setFeedback(null);await new Promise(r=>setTimeout(r,220));try{const ok=fn();setFeedback(ok===false?{tone:"error",text:"The action could not be saved."}:{tone:"success",text:"Changes saved locally."});}catch{setFeedback({tone:"error",text:"The action could not be completed."})}finally{setBusy("")}};
  const select=(key:string)=>{if(!anchor||end){setAnchor(key);setEnd("");return}if(key<anchor){setFeedback({tone:"error",text:"Choose an end date after the start date."});return}setEnd(key)};
  const update=(state:AvailabilityState)=>act(state,()=>selected.length?updateCalendarDates(id,selected,{state}):false);
  const special=(price:number)=>act("price",()=>selected.length&&price>=0?updateCalendarDates(id,selected,{price}):false);
  const back=search.get("from")==="rules"?`/owner/properties/${id}/availability-rules`:"/owner/properties";
  const exportFile=()=>act("export",()=>{const blob=new Blob([JSON.stringify({propertyId:id,dates:property.dates},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`dar-property-${id}-availability.json`;a.click();URL.revokeObjectURL(url)});
  const sync=()=>act("sync",()=>patchPropertyCalendar(id,{connections:{...property.connections,lastSync:new Date().toLocaleString("en-EG")}}));
  const importIcal=(file?:File)=>{if(!file)return;if(!file.name.toLowerCase().endsWith(".ics")){setFeedback({tone:"error",text:"Choose a valid .ics calendar file."});return}void act("import",()=>patchPropertyCalendar(id,{connections:{...property.connections,ical:true,lastSync:new Date().toLocaleString("en-EG")}}))};
  return <div className="min-h-screen bg-[#f7f8fb] text-[#11183b]"><div className="owner-dashboard-content"><div className="flex items-start justify-between gap-4 max-[760px]:block"><div><h1 className="owner-page-title">Calendar management</h1><p className="owner-page-description mt-[5px]">Manage availability, pricing, blocked dates and booking requests across your listings.</p></div><div className="flex flex-wrap justify-end gap-[8px] max-[760px]:mt-4 max-[760px]:justify-start"><Action busy={busy==="sync"} onClick={sync} icon="refresh">Sync calendar</Action><Action busy={busy==="export"} onClick={exportFile} icon="download">Export availability</Action><Action primary busy={busy==="blocked"} onClick={()=>selected.length?void update("blocked"):setFeedback({tone:"error",text:"Select dates before blocking them."})} icon="plus">Add blocked dates</Action></div></div>{feedback?<p role="status" className={`owner-body mt-3 rounded-[6px] border px-3 py-2 ${feedback.tone==="success"?"border-green-200 bg-green-50 text-green-700":"border-red-200 bg-red-50 text-red-700"}`}>{feedback.text}</p>:null}<Filters id={id} options={propertyOptions} view={store.view} display={store.display} onProperty={next=>router.push(`/owner/properties/${next}/calendar-management`)} onView={view=>patchOwnerCalendar({view})} onDisplay={display=>display==="pricing"?router.push(`/owner/properties/${id}/seasonal-pricing`):patchOwnerCalendar({display})}/><div className="mt-5 grid grid-cols-[minmax(0,1fr)_340px] gap-4 max-[1000px]:grid-cols-1"><ReferenceCalendar cursor={cursor} property={property} bookings={bookings} selected={selected} view={store.view} display={store.display} onSelect={select} onMove={n=>setCursor(c=>new Date(c.getFullYear(),c.getMonth()+n,1))} onMonth={date=>setCursor(date)}/><ReferenceBookingPanel id={id} title={propertyOptions.find(x=>x.id===id)?.name??draft.title} location={propertyOptions.find(x=>x.id===id)?.location??draft.city} property={property} selected={selected} booking={selectedBooking} onCancel={()=>update("unavailable")}/></div><DashboardLower id={id} property={property} bookings={bookings} onPatch={patch=>patchPropertyCalendar(id,patch)} onImport={()=>fileRef.current?.click()} onFeedback={setFeedback}/><input ref={fileRef} type="file" accept="text/calendar,.ics" className="sr-only" onChange={e=>importIcal(e.target.files?.[0])}/><Notes id={id} property={property} selected={selected}/><BulkActions selected={selected} busy={busy} onUpdate={update} onPrice={special}/><Link href={back} className="owner-body mt-4 inline-flex items-center gap-2 rounded focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--brand)]"><Icon name="arrow-left" className="size-[14px]"/>Back</Link></div></div>;
}

function Action({children,icon,onClick,busy,primary=false}:{children:React.ReactNode;icon:string;onClick:()=>void;busy:boolean;primary?:boolean}){return <button disabled={busy} onClick={onClick} className={`owner-button-text flex h-[34px] items-center gap-2 rounded-[5px] border px-[13px] transition hover:shadow-[var(--shadow-sm)] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--brand)] active:scale-[.99] disabled:cursor-not-allowed disabled:opacity-50 ${primary?"border-transparent bg-[#5824e6] px-[16px] text-white":"border-[#dce1eb]"}`}><Icon name={busy?"refresh":icon} className={`size-[14px] ${busy?"animate-spin":""}`}/>{children}</button>}
function Filters({id,options,view,display,onProperty,onView,onDisplay}:{id:string;options:{id:string;name:string;location:string}[];view:CalendarView;display:CalendarDisplay;onProperty:(id:string)=>void;onView:(v:CalendarView)=>void;onDisplay:(v:CalendarDisplay)=>void}){return <section className="mt-[16px] grid grid-cols-[1.15fr_.75fr_1fr] gap-[14px] rounded-[8px] border border-[#e6e9f1] bg-white p-[12px] max-[850px]:grid-cols-1"><label><b className="owner-label">Property</b><select value={id} onChange={e=>onProperty(e.target.value)} className="owner-body mt-[6px] h-[55px] w-[310px] rounded-[7px] border border-[#e0e4ed] bg-white px-3 focus-visible:outline-2 focus-visible:outline-[var(--brand)] max-[760px]:w-full">{options.map(x=><option key={x.id} value={x.id}>{x.name} — {x.location}</option>)}</select></label><Segment label="View" items={[["month","Month"],["week","Week"],["day","Day"]]} value={view} set={v=>onView(v as CalendarView)}/><Segment label="Display" items={[["calendar","Calendar"],["list","List view"],["pricing","Pricing view"]]} value={display} set={v=>onDisplay(v as CalendarDisplay)}/></section>}
function Segment({label,items,value,set}:{label:string;items:string[][];value:string;set:(v:string)=>void}){return <div><b className="owner-label">{label}</b><div role="tablist" aria-label={label} className="mt-[6px] flex h-[36px] rounded-[6px] border border-[#e1e5ed] p-[3px]">{items.map(([key,text])=><button role="tab" aria-selected={value===key} key={key} onClick={()=>set(key)} className={`owner-button-text flex-1 rounded-[4px] focus-visible:outline-2 focus-visible:outline-[var(--brand)] ${value===key?"border border-[#7040ef] bg-[#f5f0ff] text-[var(--brand)]":"text-[#68718d] hover:bg-[#faf8ff]"}`}>{text}</button>)}</div></div>}
