"use client";

import Image from "next/image";
import {useRouter} from "next/navigation";
import {useState} from "react";
import {Icon} from "@/components/host-landing/icons";
import type {OwnerBooking} from "@/lib/owner-bookings";
import {updateCalendarDates,type AvailabilityState,type PropertyCalendar} from "@/lib/owner-calendar";
import {AnalyticsRow} from "./analytics-row";

type Feedback={tone:"success"|"error";text:string};
export function DashboardLower({id,property,bookings,onPatch,onImport,onFeedback}:{id:string;property:PropertyCalendar;bookings:OwnerBooking[];onPatch:(patch:Partial<PropertyCalendar>)=>boolean;onImport:()=>void;onFeedback:(f:Feedback)=>void}){return <div className="mt-[14px] space-y-[14px]"><div className="grid grid-cols-[1.65fr_.72fr_.68fr_.72fr] gap-[12px] max-[1100px]:grid-cols-2 max-[720px]:grid-cols-1"><Upcoming bookings={bookings}/><AvailabilitySettings property={property} onPatch={onPatch}/><PricingRules id={id} property={property} onPatch={onPatch}/><CalendarSync id={id} property={property} onPatch={onPatch} onImport={onImport} onFeedback={onFeedback}/></div><AnalyticsRow id={id} property={property} bookings={bookings}/></div>}
function Card({children}:{children:React.ReactNode}){return <section className="min-h-[218px] rounded-[8px] border border-[#e4e8ef] bg-white p-[13px] shadow-[0_3px_12px_rgba(31,38,72,.025)] transition-shadow hover:shadow-[var(--shadow-sm)] focus-within:shadow-[var(--shadow-sm)]">{children}</section>}
function Upcoming({bookings}:{bookings:OwnerBooking[]}){const router=useRouter(),[menu,setMenu]=useState("");return <Card><h3 className="owner-card-title">Upcoming reservations</h3><div className="mt-[12px] overflow-x-auto"><table className="owner-body w-full min-w-[520px] table-fixed text-left"><thead><tr>{["Guest","Dates","Guests","Total payout","Status","Actions"].map(x=><th key={x} className="owner-body pb-[9px]">{x}</th>)}</tr></thead><tbody>{bookings.slice(0,3).map((r,i)=><tr key={r.id} className="h-[44px] border-t border-[#edf0f5]"><td><span className="flex items-center gap-2"><Image src={["/dashboard-avatar-omar.png","/dashboard-avatar-sara.png","/dashboard-avatar-lina.png"][i]} alt="" width={30} height={30} className="size-[30px] rounded-full"/><b>{r.guest}</b></span></td><td>{r.dates}</td><td>2 guests</td><td>EGP {r.total.toLocaleString()}</td><td><span className={`owner-badge rounded-full px-2 py-1 ${r.status==="Pending"?"bg-[#fff0d5] text-[#d98a00]":r.status==="Cancelled"?"bg-red-50 text-red-600":"bg-[#e7f7ec] text-[#289552]"}`}>{r.status}</span></td><td className="relative"><div className="flex gap-2"><Tiny label="View reservation" icon="eye" onClick={()=>router.push(`/owner/bookings?booking=${r.id}`)}/><Tiny label="Message guest" icon="message" onClick={()=>router.push(`/owner/messages?booking=${r.id}`)}/><Tiny label="Change dates" icon="calendar" onClick={()=>router.push(`/owner/bookings?booking=${r.id}&action=dates`)}/><Tiny label="More options" icon="more-vertical" onClick={()=>setMenu(menu===r.id?"":r.id)}/></div>{menu===r.id?<div className="absolute right-0 z-20 mt-1 w-32 rounded border bg-white p-1 shadow-[var(--shadow-md)]"><button onClick={()=>router.push(`/owner/bookings?booking=${r.id}`)} className="w-full rounded p-2 text-left hover:bg-[#f5f0ff]">Open booking</button></div>:null}</td></tr>)}</tbody></table></div><button onClick={()=>router.push("/owner/bookings")} className="interactive mt-2">View all reservations <Icon name="chevron" className="ml-1 inline size-[11px] -rotate-90"/></button></Card>}
function Tiny({label,icon,onClick}:{label:string;icon:string;onClick:()=>void}){return <button aria-label={label} onClick={onClick} className="rounded p-1 hover:bg-[#f5f0ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]"><Icon name={icon} className="size-[12px]"/></button>}
function AvailabilitySettings({property,onPatch}:{property:PropertyCalendar;onPatch:(p:Partial<PropertyCalendar>)=>boolean}){const r=property.rules,set=<K extends keyof typeof r>(key:K,value:(typeof r)[K])=>onPatch({rules:{...r,[key]:value}});return <Card><h3 className="owner-card-title flex gap-2"><Icon name="gear" className="size-[17px]"/>Availability settings</h3><div className="owner-body mt-3 space-y-2"><Select label="Minimum nights" value={String(r.minimumNights)} options={["1","2","3","5","7"]} onChange={v=>set("minimumNights",Math.min(Number(v),r.maximumNights))}/><Select label="Maximum nights" value={String(r.maximumNights)} options={["7","14","30","60","90"]} onChange={v=>set("maximumNights",Math.max(Number(v),r.minimumNights))}/><Select label="Advance notice" value={r.advanceNotice} options={["None","1 day","2 days","3 days","7 days"]} onChange={v=>set("advanceNotice",v)}/><Toggle label="Same-day booking" on={r.sameDay} set={v=>set("sameDay",v)}/><Toggle label="Instant booking" on={r.instant} set={v=>set("instant",v)}/><b className="owner-label block pt-1">Check-in allowed</b><div className="grid grid-cols-7 gap-[3px]">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(day=><button aria-pressed={r.checkInDays.includes(day)} key={day} onClick={()=>set("checkInDays",r.checkInDays.includes(day)?r.checkInDays.filter(x=>x!==day):[...r.checkInDays,day])} className={`h-[25px] rounded-[4px] focus-visible:outline-2 focus-visible:outline-[var(--brand)] ${r.checkInDays.includes(day)?"bg-[#6033dd] text-white":"border border-[#dfe3eb]"}`}>{day}</button>)}</div></div></Card>}
function Select({label,value,options,onChange}:{label:string;value:string;options:string[];onChange:(v:string)=>void}){return <label className="flex items-center justify-between"><span>{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="h-[27px] w-[82px] rounded-[5px] border border-[#dfe3eb] bg-white px-2 focus-visible:outline-2 focus-visible:outline-[var(--brand)]">{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Toggle({label,on,set}:{label:string;on:boolean;set:(v:boolean)=>void}){return <div className="flex items-center justify-between"><span>{label}</span><button role="switch" aria-label={label} aria-checked={on} onClick={()=>set(!on)} className={`flex h-[18px] w-[32px] items-center rounded-full p-[2px] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--brand)] ${on?"justify-end bg-[#6033dd]":"justify-start bg-[#d8dce5]"}`}><i className="size-[14px] rounded-full bg-white"/></button></div>}
function PricingRules({id,property,onPatch}:{id:string;property:PropertyCalendar;onPatch:(p:Partial<PropertyCalendar>)=>boolean}){const router=useRouter(),p=property.pricing,edit=(key:keyof typeof p,label:string,max?:number)=>{const raw=prompt(label,String(p[key]));if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<0||(max!==undefined&&value>max)){alert("Enter a valid non-negative value.");return}onPatch({pricing:{...p,[key]:value}})};return <Card><h3 className="owner-card-title flex gap-2"><Icon name="dollar" className="size-[17px]"/>Pricing rules</h3><div className="owner-body mt-3 space-y-2">{[["Base nightly price","base",`EGP ${p.base.toLocaleString()}`],["Weekend price","weekend",`EGP ${p.weekend.toLocaleString()}`],["Weekly discount","weeklyDiscount",`${p.weeklyDiscount}%`],["Monthly discount","monthlyDiscount",`${p.monthlyDiscount}%`]].map(([label,key,value])=><button key={key} onClick={()=>edit(key as keyof typeof p,label,key.includes("Discount")?100:undefined)} className="flex w-full justify-between rounded px-1 py-1 hover:bg-[#f7f3ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]"><span>{label}</span><b>{value}</b></button>)}<button onClick={()=>router.push(`/owner/properties/${id}/seasonal-pricing`)} className="flex w-full justify-between rounded px-1 py-1 hover:bg-[#f7f3ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]"><span>Special price dates</span><b>{Object.values(property.dates).filter(x=>x.price!==undefined).length} active</b></button><hr/><p className="flex justify-between"><span>Price sync status</span><b className="rounded-full bg-[#e7f7ec] px-2 py-1 text-[#289552]">Up to date</b></p></div></Card>}
function CalendarSync({id,property,onPatch,onImport,onFeedback}:{id:string;property:PropertyCalendar;onPatch:(p:Partial<PropertyCalendar>)=>boolean;onImport:()=>void;onFeedback:(f:Feedback)=>void}){const c=property.connections,copy=async()=>{try{await navigator.clipboard.writeText(`${location.origin}/calendar/owner/${id}.ics`);onFeedback({tone:"success",text:"Export link copied."})}catch{onFeedback({tone:"error",text:"Clipboard access was denied."})}};return <Card><h3 className="owner-card-title flex gap-2"><Icon name="refresh" className="size-[17px]"/>Calendar sync</h3><b className="owner-label mt-3 block">Connected calendars</b><div className="mt-2 space-y-1">{[["Google Calendar","google"],["iCal Import","ical"],["External sync","external"]].map(([name,key])=>{const connected=c[key as "google"|"ical"|"external"];return <button key={key} onClick={()=>onPatch({connections:{...c,[key]:!connected}})} className="flex h-[34px] w-full items-center rounded-[5px] border px-2 hover:bg-[#faf8ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]"><b>{name}</b><span className="ml-auto">{connected?"Connected":"Not connected"}</span></button>})}</div><p className="owner-body mt-2">Last sync: {c.lastSync}</p><div className="mt-2 grid grid-cols-2 gap-2"><button onClick={onImport} className="interactive border">Import iCal</button><button onClick={()=>void copy()} className="interactive border">Copy export link</button></div></Card>}

export function Notes({id,property,selected}:{id:string;property:PropertyCalendar;selected:string[]}){const [editing,setEditing]=useState(false),key=selected[0]??"",[text,setText]=useState(""),note=key?property.dates[key]?.note??"":"";const open=()=>{setText(note);setEditing(true)},save=()=>{if(key)updateCalendarDates(id,selected,{note:text});setEditing(false)};return <section className="owner-body mt-[14px] rounded-[8px] border border-[#e6e9f1] p-[13px] transition-shadow hover:shadow-[var(--shadow-sm)]"><div className="flex justify-between"><b>Notes for selected dates <span className="owner-body">({selected.length?`${format(selected[0])}${selected.length>1?` – ${format(selected.at(-1)!)}`:""}`:"No dates selected"})</span></b><button disabled={!selected.length} onClick={open} className="interactive disabled:opacity-40">Edit note <Icon name="pencil" className="inline size-3"/></button></div>{editing?<div className="mt-2"><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} className="w-full rounded border p-2 focus-visible:outline-2 focus-visible:outline-[var(--brand)]"/><div className="mt-2 flex justify-end gap-2"><button onClick={()=>setEditing(false)} className="interactive border">Cancel</button><button onClick={save} className="interactive bg-[#6033dd] text-white">Save note</button></div></div>:<p className="mt-2">{note||"No note for the selected dates."}</p>}</section>}
export function BulkActions({selected,busy,onUpdate,onPrice}:{selected:string[];busy:string;onUpdate:(s:AvailabilityState)=>void;onPrice:(n:number)=>void}){const price=()=>{const raw=prompt("Special nightly price (EGP)");if(raw===null)return;const value=Number(raw);if(!Number.isFinite(value)||value<0){alert("Enter a valid non-negative price.");return}onPrice(value)};return <section className="mt-[14px] flex min-h-[62px] flex-wrap items-center gap-[10px] rounded-[8px] border border-[#e6e9f1] px-[14px]"><b className="owner-label mr-auto">Bulk actions for selected range <span className="owner-body">({selected.length?`${selected.length} dates selected`:"No dates selected"})</span></b><Bulk disabled={!selected.length||!!busy} onClick={()=>onUpdate("blocked")} dark>Block selected dates</Bulk><Bulk disabled={!selected.length||!!busy} onClick={price}>Set special price</Bulk><Bulk disabled={!selected.length||!!busy} onClick={()=>onUpdate("unavailable")} red>Mark unavailable</Bulk><Bulk disabled={!selected.length||!!busy} onClick={()=>onUpdate("available")} green>Reopen dates</Bulk></section>}
function Bulk({children,onClick,disabled,dark,red,green}:{children:React.ReactNode;onClick:()=>void;disabled:boolean;dark?:boolean;red?:boolean;green?:boolean}){return <button disabled={disabled} onClick={onClick} className={`interactive border px-4 disabled:cursor-not-allowed disabled:opacity-40 ${dark?"border-transparent bg-[#343b4d] text-white":red?"border-red-400 text-red-500":green?"border-green-500 text-green-600":"border-[#6840ef]"}`}>{children}</button>}
function format(key:string){return new Date(`${key}T12:00:00`).toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}
