"use client";

import Image from "next/image";
import Link from "next/link";
import {useState} from "react";
import {Icon} from "@/components/host-landing/icons";
import {AnalyticsRow} from "./analytics-row";

type Update=(state:"available"|"booked"|"blocked")=>void;

export function DashboardLower(){return <div className="mt-[14px] space-y-[14px]"><div className="grid grid-cols-[1.65fr_.72fr_.68fr_.72fr] gap-[12px] max-[1100px]:grid-cols-2 max-[720px]:grid-cols-1"><Upcoming/><AvailabilitySettings/><PricingRules/><CalendarSync/></div><AnalyticsRow/></div>}

function Card({children}:{children:React.ReactNode}){return <section className="min-h-[218px] rounded-[8px] border border-[#e4e8ef] bg-white p-[13px] shadow-[0_3px_12px_rgba(31,38,72,.025)]">{children}</section>}
function Upcoming(){const rows=[{name:"Ismail Negm",avatar:"/dashboard-avatar-omar.png",dates:"May 20 – May 25, 2026",guests:"2 guests",payout:"EGP 5,733",status:"Confirmed"},{name:"Sara Ali",avatar:"/dashboard-avatar-sara.png",dates:"May 27 – May 29, 2026",guests:"1 guest",payout:"EGP 2,478",status:"Pending"},{name:"Lina Sameh",avatar:"/dashboard-avatar-lina.png",dates:"Jun 02 – Jun 05, 2026",guests:"2 guests",payout:"EGP 4,960",status:"Confirmed"}];return <Card><h3 className="owner-card-title">Upcoming reservations</h3><div className="mt-[12px] overflow-x-auto"><table className="owner-body w-full min-w-[520px] table-fixed text-left"><colgroup><col className="w-[25%]"/><col className="w-[23%]"/><col className="w-[12%]"/><col className="w-[14%]"/><col className="w-[13%]"/><col className="w-[13%]"/></colgroup><thead className="text-[#737c94]"><tr>{["Guest","Dates","Guests","Total payout","Status","Actions"].map(x=><th key={x} className="owner-body pb-[9px]">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.name} className="h-[44px] border-t border-[#edf0f5]"><td><span className="owner-body flex items-center gap-[8px]"><Image src={r.avatar} alt={r.name} width={30} height={30} className="size-[30px] rounded-full object-cover"/><b className="owner-label truncate">{r.name}</b></span></td><td>{r.dates}</td><td>{r.guests}</td><td className="owner-body">{r.payout}</td><td><span className={`owner-badge inline-flex rounded-full px-[8px] py-[4px] ${r.status==="Pending"?"bg-[#fff0d5] text-[#d98a00]":"bg-[#e7f7ec] text-[#289552]"}`}>{r.status}</span></td><td><span className="owner-body flex items-center gap-[6px]"><button aria-label="View reservation"><Icon name="eye" className="size-[12px]"/></button><button aria-label="Message guest"><Icon name="message" className="size-[12px]"/></button><button aria-label="Change dates"><Icon name="calendar" className="size-[12px]"/></button><button aria-label="More options" className="owner-button-text"><Icon name="more-vertical" className="size-[12px]"/></button></span></td></tr>)}</tbody></table></div><button className="owner-button-text mt-[8px]">View all reservations <Icon name="chevron" className="ml-1 inline size-[11px] -rotate-90"/></button></Card>}

function SelectControl({value}:{value:string}){return <button className="owner-button-text flex h-[26px] w-[82px] items-center justify-between rounded-[5px] border border-[#dfe3eb] bg-white px-[8px]">{value}<Icon name="chevron" className="size-[9px]"/></button>}
function Switch({on,set}:{on:boolean;set:(v:boolean)=>void}){return <button onClick={()=>set(!on)} className={`flex h-[16px] w-[30px] items-center rounded-full p-[2px] ${on?"justify-end bg-[#6033dd]":"justify-start bg-[#d8dce5]"}`}><i className="size-[12px] rounded-full bg-white"/></button>}
function AvailabilitySettings(){const [sameDay,setSameDay]=useState(false);const [instant,setInstant]=useState(true);return <Card><h3 className="owner-card-title flex items-center gap-[8px]"><Icon name="gear" className="size-[17px] text-[#4e5871]"/>Availability settings</h3><div className="owner-body mt-[13px] space-y-[7px]">{[["Minimum nights","2"],["Maximum nights","30"],["Advance notice","1 day"]].map(([a,b])=><div key={a} className="flex items-center justify-between"><span>{a}</span><SelectControl value={b}/></div>)}<div className="flex items-center justify-between pt-[3px]"><span>Same-day booking</span><Switch on={sameDay} set={setSameDay}/></div><div className="flex items-center justify-between"><span>Instant booking</span><Switch on={instant} set={setInstant}/></div><b className="owner-label block pt-[3px]">Check-in allowed</b><div className="grid grid-cols-7 gap-[3px]">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(x=><button key={x} className="owner-button-text h-[25px] rounded-[4px] bg-[#6033dd] text-white">{x}</button>)}</div></div></Card>}

function PricingRules(){return <Card><h3 className="owner-card-title flex items-center gap-[8px]"><Icon name="dollar" className="size-[17px] text-[#4e5871]"/>Pricing rules</h3><div className="owner-body mt-[13px] space-y-[10px]">{[["Base nightly price","EGP 1,200"],["Weekend price","EGP 1,400"],["Weekly discount","5%"],["Monthly discount","10%"]].map(([a,b])=><p key={a} className="owner-body flex justify-between"><span>{a}</span><b>{b}</b></p>)}<p className="owner-body flex justify-between"><span>Special price dates</span><Link href="/owner/properties/1/seasonal-pricing" className="owner-body">2 active</Link></p><hr className="border-[#edf0f5]"/><p className="owner-body flex items-center justify-between"><span>Price sync status</span><b className="owner-label inline-flex h-[22px] items-center gap-[5px] rounded-full bg-[#e7f7ec] px-[9px]"><span className="grid size-[11px] place-items-center rounded-full bg-[#28a85d] text-white"><Icon name="check" className="size-[7px]" strokeWidth="2.4"/></span>Up to date</b></p></div></Card>}

function CalendarSync(){return <Card><h3 className="owner-card-title flex items-center gap-[8px]"><Icon name="refresh" className="size-[17px] text-[#4e5871]"/>Calendar sync</h3><b className="owner-label mt-[13px] block">Connected calendars</b><div className="mt-[7px] space-y-[5px]">{[{name:"Google Calendar",icon:"G",status:"Connected",green:true},{name:"iCal Import",icon:"calendar",status:"Connected",green:true},{name:"External sync",icon:"id-link",status:"Not connected",green:false}].map(r=><div key={r.name} className="owner-body flex h-[34px] items-center rounded-[5px] border border-[#e1e5ec] px-[8px]"><span className="owner-body mr-[8px] grid size-[18px] place-items-center rounded-[4px]">{r.icon==="G"?"G":<Icon name={r.icon} className="size-[15px] text-[#59637b]"/>}</span><b>{r.name}</b><span className={`owner-body ml-auto ${r.green?"text-[#289552]":"text-[#737b91]"}`}>{r.status}</span></div>)}</div><p className="owner-body mt-[9px]">Last sync: Today, 10:24 AM</p><div className="mt-[9px] grid grid-cols-2 gap-[7px]"><button className="owner-button-text h-[31px] rounded-[5px] border border-[#8e6bf2]">Import iCal</button><button className="owner-button-text flex h-[31px] items-center justify-center gap-[5px] rounded-[5px] border border-[#8e6bf2]"><Icon name="id-link" className="size-[12px]"/>Copy export link</button></div></Card>}


export function Notes(){return <section className="owner-body mt-[14px] rounded-[8px] border border-[#e6e9f1] p-[13px]"><div className="flex justify-between"><b>Notes for selected dates <span className="owner-body">(May 20 – May 25, 2026)</span></b><button className="owner-button-text inline-flex items-center gap-1">Edit note<Icon name="pencil" className="size-[12px]"/></button></div><p className="owner-body mt-2">Returning guest. Prefers quiet environment. Late check-in expected around 9 PM.</p></section>}
export function BulkActions({selected,onUpdate}:{selected:string[];onUpdate:Update}){return <section className="mt-[14px] flex min-h-[62px] flex-wrap items-center gap-[10px] rounded-[8px] border border-[#e6e9f1] px-[14px]"><b className="owner-label mr-auto">Bulk actions for selected range <span className="owner-body">({selected.length?`${selected.length} dates selected`:"May 20 – May 25, 2026"})</span></b><button onClick={()=>onUpdate("blocked")} className="owner-button-text h-[34px] rounded-[5px] bg-[#343b4d] px-4 text-white">Block selected dates</button><button className="owner-button-text h-[34px] rounded-[5px] border border-[#6840ef] px-4">Set special price</button><button onClick={()=>onUpdate("blocked")} className="owner-button-text h-[34px] rounded-[5px] border border-red-400 px-4 text-red-500">Mark unavailable</button><button onClick={()=>onUpdate("available")} className="owner-button-text h-[34px] rounded-[5px] border border-green-500 px-4 text-green-600">Reopen dates</button></section>}
