"use client";

import {useMemo,useState} from "react";
import {Icon} from "@/components/host-landing/icons";
import type {OwnerBooking} from "@/lib/owner-bookings";
import type {CalendarDisplay,CalendarView,PropertyCalendar} from "@/lib/owner-calendar";

type Cell={key:string;day:number;muted:boolean;kind:"available"|"booked"|"pending"|"blocked"|"unavailable"|"hold";guest?:string;price:number;special:boolean};
export function ReferenceCalendar({cursor,property,bookings,selected,view,display,onSelect,onMove,onMonth}:{cursor:Date;property:PropertyCalendar;bookings:OwnerBooking[];selected:string[];view:CalendarView;display:CalendarDisplay;onSelect:(key:string)=>void;onMove:(delta:number)=>void;onMonth:(date:Date)=>void}){
  const cells=useMemo(()=>build(cursor,property,bookings),[cursor,property,bookings]),[monthOpen,setMonthOpen]=useState(false),visible=view==="month"?cells:view==="week"?weekFor(cells,selected[0]??`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}-20`):cells.filter(x=>x.key===(selected[0]??`${cursor.getFullYear()}-${String(cursor.getMonth()+1).padStart(2,"0")}-20`));
  return <section className="overflow-hidden rounded-[8px] border border-[#e3e7ef] bg-white transition-shadow hover:shadow-[var(--shadow-sm)]"><div className="flex min-h-[52px] flex-wrap items-center gap-[9px] border-b border-[#e8ebf2] px-[11px]"><Nav label="Previous month" onClick={()=>onMove(-1)} rotate="rotate-90"/><Nav label="Next month" onClick={()=>onMove(1)} rotate="-rotate-90"/><div className="relative"><button aria-expanded={monthOpen} onClick={()=>setMonthOpen(x=>!x)} className="owner-label ml-[4px] flex items-center gap-2 rounded px-2 py-1 hover:bg-[#f7f3ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]">{cursor.toLocaleDateString("en-US",{month:"long",year:"numeric"})}<Icon name="chevron" className="size-[10px]"/></button>{monthOpen?<div className="absolute left-1 top-full z-30 mt-1 grid w-[220px] grid-cols-3 gap-1 rounded-[7px] border border-[#e3e7ef] bg-white p-2 shadow-[var(--shadow-md)]">{Array.from({length:12},(_,m)=><button key={m} onClick={()=>{onMonth(new Date(cursor.getFullYear(),m,1));setMonthOpen(false)}} className="owner-body rounded px-2 py-2 hover:bg-[#f5f0ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]">{new Date(2026,m,1).toLocaleDateString("en",{month:"short"})}</button>)}</div>:null}</div><Legend/></div>{display==="list"?<List cells={visible} onSelect={onSelect}/>:<div className="max-[620px]:overflow-x-auto"><div className={view==="day"?"min-w-[280px]":view==="week"?"grid min-w-[620px] grid-cols-7":"min-w-[680px]"}>{view!=="day"?<div className="grid grid-cols-7 border-b border-[#e8ebf2] bg-[#fafbfe]">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div className="owner-body py-[8px] text-center text-[#596382]" key={x}>{x}</div>)}</div>:null}<div role="grid" aria-label={`${view} ${display} calendar`} className={view==="day"?"grid grid-cols-1":view==="week"?"contents":"grid grid-cols-7"}>{visible.map(cell=><CalendarCell key={cell.key} cell={cell} selected={selected.includes(cell.key)} pricing={display==="pricing"} onSelect={onSelect}/>)}</div></div></div>}</section>;
}
function Nav({label,onClick,rotate}:{label:string;onClick:()=>void;rotate:string}){return <button aria-label={label} onClick={onClick} className="grid size-[28px] place-items-center rounded-[5px] border border-[#dce1eb] hover:bg-[#f7f3ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)] active:bg-[#eee7ff]"><Icon name="chevron" className={`size-[10px] ${rotate}`}/></button>}
function Legend(){return <div className="owner-body ml-auto flex flex-wrap items-center gap-[13px] text-[#58617d]">{[["#35a853","Available"],["#6033dd","Booked"],["#ffa21a","Pending request"],["#9ca0a9","Owner blocked"],["#e4252b","DAR hold"],["#387bf0","Special price"]].map(([color,label])=><span key={label} className="owner-body flex items-center gap-[5px]"><i className="size-[7px] rounded-full" style={{background:color}}/>{label}</span>)}</div>}
function build(cursor:Date,property:PropertyCalendar,bookings:OwnerBooking[]){const y=cursor.getFullYear(),m=cursor.getMonth(),offset=new Date(y,m,1).getDay(),cells:Cell[]=[];for(let i=0;i<42;i++){const d=new Date(y,m,1-offset+i),day=d.getDate(),muted=d.getMonth()!==m,key=d.toISOString().slice(0,10),saved=property.dates[key];let kind:Cell["kind"]=saved?.state??"available",guest:string|undefined;if(!saved?.state&&!muted&&day>=20&&day<=23){kind="booked";guest=bookings.find(x=>x.status==="Confirmed")?.guest??"Ismail Negm"}if(!saved?.state&&!muted&&day>=27&&day<=29){kind="pending";guest=bookings.find(x=>x.status==="Pending")?.guest??"Sara Ali"}if(!saved?.state&&muted&&d.getMonth()===5&&day===4)kind="hold";const price=saved?.price??(d.getDay()===5||d.getDay()===6?property.pricing.weekend:property.pricing.base);cells.push({key,day,muted,kind,guest,price,special:saved?.price!==undefined})}return cells}
function weekFor(cells:Cell[],key:string){const index=Math.max(0,cells.findIndex(x=>x.key===key));return cells.slice(Math.floor(index/7)*7,Math.floor(index/7)*7+7)}
function CalendarCell({cell,selected,pricing,onSelect}:{cell:Cell;selected:boolean;pricing:boolean;onSelect:(key:string)=>void}){const unavailable=cell.kind==="hold";return <button role="gridcell" aria-selected={selected} disabled={unavailable} onClick={()=>onSelect(cell.key)} className={`relative min-h-[62px] border-b border-r border-[#e8ebf2] p-[7px] text-left transition hover:brightness-[.98] focus-visible:z-20 focus-visible:outline-2 focus-visible:outline-[var(--brand)] disabled:cursor-not-allowed ${cell.muted&&cell.kind!=="hold"?"bg-[#fbfcfe] text-[#b4bac8]":""} ${cell.kind==="booked"?"bg-gradient-to-r from-[var(--brand)] to-[#7142eb] text-white":cell.kind==="pending"?"bg-gradient-to-r from-[#f49b12] to-[#ffae20] text-white":cell.kind==="blocked"||cell.kind==="unavailable"?"bg-[repeating-linear-gradient(135deg,#3d4451,#3d4451_6px,#464e5c_6px,#464e5c_8px)] text-white":selected?"bg-[#f4efff] ring-2 ring-inset ring-[#6332ee]":"bg-white"}`}><b className="owner-button-text block">{cell.day}</b><span className="owner-body mt-[7px] block truncate">{pricing?`EGP ${cell.price.toLocaleString()}`:cell.kind==="blocked"||cell.kind==="unavailable"?"Owner blocked":cell.kind==="booked"||cell.kind==="pending"?cell.guest:cell.kind==="hold"?"DAR hold":`EGP ${cell.price.toLocaleString()}`}</span>{cell.special?<i aria-label="Special price" className="absolute right-[6px] top-[7px] grid size-[9px] place-items-center rounded-full bg-[#397df0] text-[5px] font-bold text-white">$</i>:null}</button>}
function List({cells,onSelect}:{cells:Cell[];onSelect:(key:string)=>void}){return <div className="max-h-[430px] overflow-auto">{cells.filter(x=>!x.muted).map(cell=><button key={cell.key} onClick={()=>onSelect(cell.key)} className="owner-body flex w-full items-center border-b border-[#edf0f5] px-4 py-3 text-left hover:bg-[#faf8ff] focus-visible:outline-2 focus-visible:outline-[var(--brand)]"><b>{new Date(`${cell.key}T12:00:00`).toLocaleDateString("en-US",{weekday:"short",month:"short",day:"numeric"})}</b><span className="ml-auto capitalize">{cell.kind}</span><b className="ml-6">EGP {cell.price.toLocaleString()}</b></button>)}</div>}
