"use client";

import {useMemo} from "react";
import {Icon} from "@/components/host-landing/icons";

type State="available"|"booked"|"blocked";
type Cell={key:string;day:number;month:number;muted:boolean;kind:"available"|"booked"|"pending"|"blocked"|"hold";guest?:string;price?:number;special?:boolean};

export function ReferenceCalendar({cursor,saved,selected,onSelect,onMove}:{cursor:Date;saved:Record<string,State>;selected:string[];onSelect:(key:string)=>void;onMove:(delta:number)=>void}){const cells=useMemo(()=>build(cursor),[cursor]);return <section className="overflow-hidden rounded-[8px] border border-[#e3e7ef] bg-white"><div className="flex min-h-[52px] flex-wrap items-center gap-[9px] border-b border-[#e8ebf2] px-[11px]"><button aria-label="Previous month" onClick={()=>onMove(-1)} className="grid size-[28px] place-items-center rounded-[5px] border border-[#dce1eb]"><Icon name="chevron" className="size-[10px] rotate-90"/></button><button aria-label="Next month" onClick={()=>onMove(1)} className="grid size-[28px] place-items-center rounded-[5px] border border-[#dce1eb]"><Icon name="chevron" className="size-[10px] -rotate-90"/></button><b className="owner-label ml-[4px]">{cursor.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</b><Icon name="chevron" className="size-[10px]"/><Legend/></div><div className="grid grid-cols-7 border-b border-[#e8ebf2] bg-[#fafbfe]">{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div className="owner-body py-[8px] text-center text-[#596382]" key={x}>{x}</div>)}</div><div className="grid grid-cols-7">{cells.map(cell=><CalendarCell key={cell.key} cell={cell} override={saved[cell.key]} selected={selected.includes(cell.key)} onSelect={onSelect}/>)}</div></section>}
function Legend(){return <div className="owner-body ml-auto flex flex-wrap items-center gap-[13px] text-[#58617d]">{[["#35a853","Available"],["#6033dd","Booked"],["#ffa21a","Pending request"],["#9ca0a9","Owner blocked"],["#e4252b","DAR hold"],["#387bf0","Special price"]].map(([color,label])=><span key={label} className="owner-body flex items-center gap-[5px]"><i className="size-[7px] rounded-full" style={{background:color}}/>{label}</span>)}</div>}
function build(cursor:Date){const y=cursor.getFullYear(),m=cursor.getMonth(),offset=new Date(y,m,1).getDay(),cells:Cell[]=[];for(let i=0;i<42;i++){const d=new Date(y,m,1-offset+i),day=d.getDate(),muted=d.getMonth()!==m,key=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(day).padStart(2,"0")}`;let kind:Cell["kind"]="available",guest:string|undefined;if(!muted&&day>=10&&day<=12){kind="booked";guest="Omar Nabil"}if(!muted&&day>=20&&day<=23){kind="booked";guest="Ismail Negm"}if(!muted&&day===25){kind="booked";guest="Ismail Negm"}if(!muted&&day>=27&&day<=29){kind="pending";guest="Sara Ali"}if(!muted&&day===31)kind="blocked";if(muted&&d.getMonth()===5&&day===4)kind="hold";cells.push({key,day,month:d.getMonth(),muted,kind,guest,price:day%3===0?1300:1200,special:[3,4,9,18,30].includes(day)})}return cells}
function CalendarCell({cell,override,selected,onSelect}:{cell:Cell;override?:State;selected:boolean;onSelect:(key:string)=>void}){let kind=cell.kind;if(override==="blocked")kind="blocked";if(override==="available")kind="available";const colored=kind==="booked"||kind==="pending"||kind==="blocked";return <button onClick={()=>kind!=="hold"&&onSelect(cell.key)} className={`relative min-h-[62px] border-b border-r border-[#e8ebf2] p-[7px] text-left max-[760px]:min-h-[58px] max-[760px]:p-[4px] ${cell.muted&&kind!=="hold"?"bg-[#fbfcfe] text-[#b4bac8]":""} ${kind==="booked"?"bg-gradient-to-r from-[var(--brand)] to-[#7142eb] text-white":kind==="pending"?"bg-gradient-to-r from-[#f49b12] to-[#ffae20] text-white":kind==="blocked"?"bg-[repeating-linear-gradient(135deg,#3d4451,#3d4451_6px,#464e5c_6px,#464e5c_8px)] text-white":selected?"bg-[#f4efff] ring-2 ring-inset ring-[#6332ee]":"bg-white"}`}><b className="owner-button-text block">{cell.day}</b>{colored?<span className="owner-body mt-[7px] block truncate">{kind==="blocked"?"Owner blocked":cell.guest}</span>:kind==="hold"?<span className="owner-body mt-[7px] flex items-center gap-1"><i className="size-[7px] rounded-full bg-[#e4252b]"/>DAR hold</span>:!cell.muted?<span className="owner-body mt-[7px] flex items-center gap-1"><i className="grid size-[8px] place-items-center rounded-full bg-[#397df0] text-[5px] text-white">$</i>EGP {cell.price?.toLocaleString()}</span>:null}{cell.special&&!colored&&!cell.muted?<i className="absolute right-[6px] top-[7px] grid size-[9px] place-items-center rounded-full bg-[#397df0] text-[5px] font-bold text-white">$</i>:null}</button>}

export function ReferenceBookingPanel(){return <aside className="space-y-[10px]"><section className="flex h-[48px] items-center rounded-[7px] border border-[#e3e7ef] bg-white px-[12px]"><b className="owner-label">Selected range</b><span className="owner-badge ml-auto rounded-[5px] bg-[#f1edff] px-[12px] py-[6px]">May 20 – May 25, 2026</span></section><section className="rounded-[8px] border border-[#e3e7ef] bg-white p-[12px]"><h2 className="owner-section-title">Booking details</h2><div className="mt-[13px] flex items-center"><span className="owner-badge grid size-[42px] shrink-0 place-items-center rounded-full bg-[#6d50cb] text-white"><Icon name="user" className="size-[22px]"/></span><span className="owner-body ml-[11px]"><b className="owner-label block">Ismail Negm</b><small className="owner-helper mt-1 block">2 guests</small></span><div className="ml-auto space-y-[6px]"><span className="owner-badge flex h-[28px] items-center gap-2 rounded-[5px] border border-[#e1e5ec] px-[9px]"><Icon name="calendar" className="size-[12px]"/>Check-in after 2 PM</span><span className="owner-badge flex h-[28px] items-center gap-2 rounded-[5px] border border-[#e1e5ec] px-[9px]"><span className="grid size-[12px] place-items-center rounded-full bg-[#1bb86a] text-white"><Icon name="check" className="size-[8px]" strokeWidth="2.4"/></span>Payment verified</span></div></div><hr className="my-[13px] border-[#edf0f5]"/><div className="owner-body flex items-center"><span className="owner-body">Total payout</span><b className="owner-label ml-auto">EGP 5,733</b><Icon name="info-circle" className="ml-2 size-[13px]"/></div><button className="owner-button-text mt-[12px] h-[34px] w-full rounded-[5px] bg-[#6033dd] text-white">Open booking</button><div className="mt-[9px] grid grid-cols-2 gap-[8px]"><button className="owner-button-text h-[34px] rounded-[5px] border border-[#dfe3eb]"><Icon name="message" className="mr-2 inline size-[13px]"/>Message guest</button><button className="owner-button-text h-[34px] rounded-[5px] border border-[#dfe3eb]"><Icon name="calendar" className="mr-2 inline size-[13px]"/>Change dates</button></div><button className="owner-button-text mt-[9px] flex h-[34px] w-full items-center justify-center gap-2 rounded-[5px] border border-[#ff8c8c]"><Icon name="x-circle" className="size-[13px]"/>Cancel availability</button></section></aside>}
