// Shared mock data for DAR owner portal
// TODO: Replace with real API data when backend is connected

export const properties = [
  {
    id: "1",
    name: "Modern Apartment in Zamalek",
    location: "Zamalek, Cairo, Egypt",
    status: "active",
    price: 2500,
    bookings: 12,
    rating: 4.8,
    image: "/properties/madinty-living.png",
  },
  {
    id: "2",
    name: "Luxury Villa in New Cairo",
    location: "New Cairo, Cairo, Egypt",
    status: "active",
    price: 8500,
    bookings: 5,
    rating: 4.9,
    image: "/properties/new-capital-studio.png",
  },
  {
    id: "3",
    name: "Studio in Downtown Cairo",
    location: "Downtown, Cairo, Egypt",
    status: "pending",
    price: 1500,
    bookings: 8,
    rating: 4.5,
    image: "/properties/new-capital-terrace.png",
  },
  {
    id: "4",
    name: "Serviced Apartment in Maadi",
    location: "Maadi, Cairo, Egypt",
    status: "active",
    price: 3200,
    bookings: 15,
    rating: 4.7,
    image: "/properties/madina-nour-duplex.png",
  },
];

export const payouts = [
  {
    id: "PAYOUT-8041",
    propertyId: "1",
    property: "Modern Apartment in Zamalek",
    booking: "BK-1002",
    guest: "Sara Ahmed",
    checkout: "Jun 05, 2026",
    gross: 12000,
    commission: 1680,
    net: 10320,
    method: "InstaPay",
    status: "Upcoming",
    date: "Jun 07, 2026",
  },
  {
    id: "PAYOUT-8018",
    propertyId: "4",
    property: "Serviced Apartment in Maadi",
    booking: "BK-1005",
    guest: "Nour Ahmed",
    checkout: "May 20, 2026",
    gross: 16000,
    commission: 2240,
    net: 13760,
    method: "Bank transfer",
    status: "Paid",
    date: "May 22, 2026",
  },
  {
    id: "PAYOUT-7992",
    propertyId: "2",
    property: "Luxury Villa in New Cairo",
    booking: "BK-1004",
    guest: "Khaled Hassan",
    checkout: "Jun 17, 2026",
    gross: 59500,
    commission: 8330,
    net: 51170,
    method: "Vodafone Cash",
    status: "Processing",
    date: "Jun 19, 2026",
  },
  {
    id: "PAYOUT-7950",
    propertyId: "1",
    property: "Modern Apartment in Zamalek",
    booking: "BK-1001",
    guest: "Omar Khaled",
    checkout: "May 28, 2026",
    gross: 8400,
    commission: 1176,
    net: 7224,
    method: "InstaPay",
    status: "Failed",
    date: "May 30, 2026",
  },
  {
    id: "PAYOUT-7904",
    propertyId: "3",
    property: "Studio in Downtown Cairo",
    booking: "BK-1003",
    guest: "Lina Mohamed",
    checkout: "May 22, 2026",
    gross: 3600,
    commission: 504,
    net: 3096,
    method: "InstaPay",
    status: "On hold",
    date: "May 24, 2026",
  },
];

export const bookings = [
  { id: "BK-1001", propertyId: "1", guest: "Omar Khaled", total: 8400, status: "Pending", dates: "May 25-28, 2026" },
  { id: "BK-1002", propertyId: "1", guest: "Sara Ahmed", total: 12000, status: "Confirmed", dates: "Jun 1-5, 2026" },
  { id: "BK-1003", propertyId: "3", guest: "Lina Mohamed", total: 3600, status: "Cancelled", dates: "May 20-22, 2026" },
  { id: "BK-1004", propertyId: "2", guest: "Khaled Hassan", total: 59500, status: "Pending", dates: "Jun 10-17, 2026" },
  { id: "BK-1005", propertyId: "4", guest: "Nour Ahmed", total: 16000, status: "Confirmed", dates: "May 15-20, 2026" },
  { id: "BK-1006", propertyId: "1", guest: "Mariam Ali", total: 19600, status: "Pending", dates: "Jul 1-8, 2026" },
];

export const ownerVerificationData = {
  status: "pending" as const,
  documents: [
    { name: "National ID", status: "verified" as const },
    { name: "Property Deed", status: "pending" as const },
    { name: "Utility Bill", status: "missing" as const },
  ],
};
