"use client";

import {useSyncExternalStore} from "react";

export const OWNER_CALENDAR_STORAGE_KEY="dar-owner-calendar";
const UPDATED="dar-owner-calendar-updated";
export type CalendarView="month"|"week"|"day";
export type CalendarDisplay="calendar"|"list"|"pricing";
export type AvailabilityState="available"|"blocked"|"unavailable";
export type CalendarDate={state?:AvailabilityState;price?:number;note?:string;reason?:string};
export type RuleUnit="days"|"weeks"|"months";
export type CustomDateRule={id:string;start:string;end:string;minimumNights:number;status:"Upcoming"|"Confirmed"};
export type CalendarRules={minimumNights:number;maximumNights:number;advanceNotice:string;sameDay:boolean;instant:boolean;instantBooking?:boolean;checkInDays:string[];bookingWindowValue:number;bookingWindowUnit:RuleUnit;noticeValue:number;noticeUnit:RuleUnit;weekdayMinimum:number;weekendMinimum:number;noMaximum:boolean;checkInDay:string;checkOutDay:string;gapNights:number;gapEnabled:boolean;customRules:CustomDateRule[]};
export type CalendarPricing={base:number;weekend:number;weeklyDiscount:number;monthlyDiscount:number};
export type CalendarConnection={google:boolean;ical:boolean;external:boolean;lastSync:string};
export type HousekeepingTask={id:string;date:string;task:string;done:boolean};
export type PropertyCalendar={dates:Record<string,CalendarDate>;rules:CalendarRules;pricing:CalendarPricing;connections:CalendarConnection;housekeeping:HousekeepingTask[]};
export type OwnerCalendarState={version:1;selectedPropertyId:string;view:CalendarView;display:CalendarDisplay;properties:Record<string,PropertyCalendar>};

const calendar=():PropertyCalendar=>({dates:{"2026-05-31":{state:"blocked",reason:"Owner blocked"}},rules:{minimumNights:1,maximumNights:90,advanceNotice:"1 day",sameDay:true,instant:true,checkInDays:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],bookingWindowValue:12,bookingWindowUnit:"months",noticeValue:1,noticeUnit:"days",weekdayMinimum:1,weekendMinimum:2,noMaximum:true,checkInDay:"Any day",checkOutDay:"Any day",gapNights:1,gapEnabled:true,customRules:[{id:"rule-1",start:"2025-05-20",end:"2025-05-25",minimumNights:3,status:"Upcoming"},{id:"rule-2",start:"2025-06-01",end:"2025-06-10",minimumNights:2,status:"Confirmed"}]},pricing:{base:1200,weekend:1400,weeklyDiscount:5,monthlyDiscount:10},connections:{google:true,ical:true,external:false,lastSync:"Today, 10:24 AM"},housekeeping:[{id:"h1",date:"2026-05-20",task:"Clean before 2 PM",done:false},{id:"h2",date:"2026-05-25",task:"Inspection needed",done:false},{id:"h3",date:"2026-05-29",task:"Laundry pickup",done:false}]});
export const OWNER_CALENDAR_FALLBACK:OwnerCalendarState={version:1,selectedPropertyId:"1",view:"month",display:"calendar",properties:{"1":calendar()}};

const validNumber=(v:unknown)=>typeof v==="number"&&Number.isFinite(v)&&v>=0;
function validateProperty(v:unknown):PropertyCalendar|null{if(!v||typeof v!=="object")return null;const s=v as Partial<PropertyCalendar>,fallback=calendar();if(!s.rules||!s.pricing||!s.connections||!s.dates||!Array.isArray(s.housekeeping))return null;const source=s.rules as Partial<CalendarRules>,r:CalendarRules={...fallback.rules,...source,customRules:Array.isArray(source.customRules)?source.customRules.filter((x):x is CustomDateRule=>!!x&&typeof x.id==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(x.start)&&/^\d{4}-\d{2}-\d{2}$/.test(x.end)&&validNumber(x.minimumNights)&&(x.status==="Upcoming"||x.status==="Confirmed")):fallback.rules.customRules};const p=s.pricing,c=s.connections;if(!validNumber(r.minimumNights)||!validNumber(r.maximumNights)||r.maximumNights<r.minimumNights||typeof r.advanceNotice!=="string"||typeof r.sameDay!=="boolean"||typeof r.instant!=="boolean"||!Array.isArray(r.checkInDays)||!r.checkInDays.every(x=>typeof x==="string")||!validNumber(r.bookingWindowValue)||!(["days","weeks","months"] as const).includes(r.bookingWindowUnit)||!validNumber(r.noticeValue)||!(["days","weeks","months"] as const).includes(r.noticeUnit)||!validNumber(r.weekdayMinimum)||!validNumber(r.weekendMinimum)||typeof r.noMaximum!=="boolean"||typeof r.checkInDay!=="string"||typeof r.checkOutDay!=="string"||!validNumber(r.gapNights)||typeof r.gapEnabled!=="boolean")return null;if(!validNumber(p.base)||!validNumber(p.weekend)||!validNumber(p.weeklyDiscount)||!validNumber(p.monthlyDiscount)||p.weeklyDiscount>100||p.monthlyDiscount>100)return null;if(typeof c.google!=="boolean"||typeof c.ical!=="boolean"||typeof c.external!=="boolean"||typeof c.lastSync!=="string")return null;const dates:Record<string,CalendarDate>={};for(const [k,d] of Object.entries(s.dates)){if(!/^\d{4}-\d{2}-\d{2}$/.test(k)||!d||typeof d!=="object")continue;const x=d as CalendarDate;if(x.state&&!(["available","blocked","unavailable"] as const).includes(x.state))continue;if(x.price!==undefined&&!validNumber(x.price))continue;dates[k]={state:x.state,price:x.price,note:typeof x.note==="string"?x.note:undefined,reason:typeof x.reason==="string"?x.reason:undefined};}const housekeeping=s.housekeeping.filter((x):x is HousekeepingTask=>!!x&&typeof x.id==="string"&&typeof x.date==="string"&&typeof x.task==="string"&&typeof x.done==="boolean");return {...fallback,dates,rules:r,pricing:p as CalendarPricing,connections:c as CalendarConnection,housekeeping};}
export function validateOwnerCalendar(v:unknown):OwnerCalendarState|null{if(!v||typeof v!=="object")return null;const s=v as Partial<OwnerCalendarState>;if(s.version!==1||typeof s.selectedPropertyId!=="string"||!(["month","week","day"] as const).includes(s.view as CalendarView)||!(["calendar","list","pricing"] as const).includes(s.display as CalendarDisplay)||!s.properties||typeof s.properties!=="object")return null;const properties:Record<string,PropertyCalendar>={};for(const [id,value] of Object.entries(s.properties)){const p=validateProperty(value);if(p)properties[id]=p;}if(!Object.keys(properties).length)properties["1"]=calendar();return {...s,properties} as OwnerCalendarState;}

let cachedRaw:string|null|undefined,cached=OWNER_CALENDAR_FALLBACK;
function migrateLegacy(raw:string|null){let state=raw?validateOwnerCalendar(JSON.parse(raw))??OWNER_CALENDAR_FALLBACK:OWNER_CALENDAR_FALLBACK,changed=false;for(let index=0;index<localStorage.length;index++){const key=localStorage.key(index);if(!key)continue;const availability=key.match(/^dar-owner-availability:(.+)$/),seasonal=key.match(/^dar-seasonal-pricing:(.+)$/);if(!availability&&!seasonal)continue;try{const value=JSON.parse(localStorage.getItem(key)??"{}") as Record<string,unknown>,id=(availability??seasonal)![1],property=ensurePropertyCalendar(state,id);if(availability){const minimum=Math.max(0,Number(value.weekdays)||property.rules.minimumNights),maximum=value.noMaximum?90:Math.max(minimum,Number(value.maximum)||property.rules.maximumNights);state={...state,properties:{...state.properties,[id]:{...property,rules:{...property.rules,minimumNights:minimum,maximumNights:maximum,advanceNotice:`${Number(value.notice)||0} day${Number(value.notice)===1?"":"s"}`,sameDay:typeof value.sameDay==="boolean"?value.sameDay:property.rules.sameDay,instant:typeof value.instant==="boolean"?value.instant:property.rules.instant}}}}}else{const base=Math.max(0,Number(value.base)||property.pricing.base);state={...state,properties:{...state.properties,[id]:{...property,pricing:{...property.pricing,base}}}}}localStorage.removeItem(key);index--;changed=true;}catch{localStorage.removeItem(key);index--;}}if(changed){raw=JSON.stringify(state);localStorage.setItem(OWNER_CALENDAR_STORAGE_KEY,raw)}return raw;}
void migrateLegacy;
export function readOwnerCalendar(){if(typeof window==="undefined")return OWNER_CALENDAR_FALLBACK;try{const raw=localStorage.getItem(OWNER_CALENDAR_STORAGE_KEY);if(raw===cachedRaw)return cached;cachedRaw=raw;cached=raw?validateOwnerCalendar(JSON.parse(raw))??OWNER_CALENDAR_FALLBACK:OWNER_CALENDAR_FALLBACK;}catch{cached=OWNER_CALENDAR_FALLBACK;}return cached;}
export function writeOwnerCalendar(next:OwnerCalendarState){if(typeof window==="undefined")return false;const valid=validateOwnerCalendar(next);if(!valid)return false;try{const raw=JSON.stringify(valid);localStorage.setItem(OWNER_CALENDAR_STORAGE_KEY,raw);cachedRaw=raw;cached=valid;window.dispatchEvent(new Event(UPDATED));return true;}catch{return false;}}
function subscribe(fn:()=>void){const storage=(e:StorageEvent)=>{if(e.key===OWNER_CALENDAR_STORAGE_KEY)fn()};window.addEventListener("storage",storage);window.addEventListener(UPDATED,fn);return()=>{window.removeEventListener("storage",storage);window.removeEventListener(UPDATED,fn)}}
export function useOwnerCalendar(){return useSyncExternalStore(subscribe,readOwnerCalendar,()=>OWNER_CALENDAR_FALLBACK)}
export function ensurePropertyCalendar(state:OwnerCalendarState,id:string){return state.properties[id]??calendar()}
export function patchOwnerCalendar(patch:Partial<Omit<OwnerCalendarState,"properties">>){const current=readOwnerCalendar();return writeOwnerCalendar({...current,...patch});}
export function patchPropertyCalendar(id:string,patch:Partial<PropertyCalendar>){const current=readOwnerCalendar(),base=ensurePropertyCalendar(current,id);return writeOwnerCalendar({...current,selectedPropertyId:id,properties:{...current.properties,[id]:{...base,...patch}}});}
export function updateCalendarDates(id:string,keys:string[],patch:CalendarDate){const current=readOwnerCalendar(),base=ensurePropertyCalendar(current,id),dates={...base.dates};for(const key of keys)dates[key]={...dates[key],...patch};return patchPropertyCalendar(id,{dates});}
export function calendarRange(start:string,end:string){if(!start||!end||end<start)return[];const out:string[]=[],cursor=new Date(`${start}T12:00:00`),last=new Date(`${end}T12:00:00`);while(cursor<=last&&out.length<367){out.push(cursor.toISOString().slice(0,10));cursor.setDate(cursor.getDate()+1)}return out;}
export function calendarMetrics(property:PropertyCalendar){const values=Object.values(property.dates),blocked=values.filter(x=>x.state==="blocked"||x.state==="unavailable").length,prices=values.map(x=>x.price).filter((x):x is number=>typeof x==="number");return{blocked,average:prices.length?Math.round(prices.reduce((a,b)=>a+b,0)/prices.length):property.pricing.base,special:prices.length};}
