"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { DarLogo } from "@/components/brand/dar-logo";
import { Icon } from "@/components/host-landing/icons";

export default function BookingRequestDecisionPage() {
  const router = useRouter();
  const [decision, setDecision] = useState<"approve" | "decline">("approve");
  const [message, setMessage] = useState("");
  const submit = () => router.push("/owner/bookings/request-decision");
  return <div className="min-h-screen bg-[#fafbfe] pb-[76px] text-[#11183b] lg:pb-0">
        <div className="owner-dashboard-content">
          <Link href="/owner/bookings" className="owner-body inline-flex items-center gap-2"><Icon name="arrow-left" className="size-[14px]"/>Back to bookings</Link>
          <h1 className="owner-page-title mt-[15px] tracking-[-.02em]">Booking request decision</h1>
          <p className="owner-page-description mt-[4px] max-[760px]:max-w-[270px]">Review the booking request details and make your decision.</p>
          <PropertyCard />
          <GuestCard />
          <div className="mt-[14px] grid grid-cols-[1.2fr_.95fr] rounded-[9px] border border-[#e7eaf1] max-[900px]:grid-cols-1 max-[760px]:border-0">
            <Decision decision={decision} setDecision={setDecision} />
            <Message message={message} setMessage={setMessage} />
          </div>
          <BottomActions decision={decision} submit={submit} />
        </div>
  </div>;
}

function Header(){return <><header className="flex h-[58px] items-center justify-end border-b border-[#edf0f6] px-6 max-[760px]:hidden"><span className="owner-body relative"><Icon name="bell" className="size-[18px]"/><b className="owner-label absolute -right-2 -top-2 grid size-4 place-items-center rounded-full bg-red-500 text-white">3</b></span><Image src="/publish-avatar-ahmed-reference.svg" alt="Ahmed H." width={30} height={30} className="ml-7 size-[30px] rounded-full object-cover"/><b className="owner-label ml-3">Ahmed H.</b><Icon name="chevron" className="ml-3 size-3"/></header><header className="hidden h-[64px] items-center justify-between border-b border-[#edf0f6] px-4 max-[760px]:flex"><Icon name="menu" className="size-5"/><DarLogo surface="light" width={610} height={260} className="h-[35px] w-[88px] object-contain"/><span className="owner-body relative"><Icon name="bell" className="size-5"/><b className="owner-label absolute -right-2 -top-2 grid size-4 place-items-center rounded-full bg-red-500 text-white">3</b></span></header></>}

function PropertyCard(){return <section className="mt-[15px] grid grid-cols-[170px_1fr_185px] items-center gap-[18px] rounded-[9px] border border-[#e7eaf1] p-[12px] shadow-[0_5px_18px_rgba(28,37,70,.025)] max-[760px]:grid-cols-[78px_1fr] max-[760px]:gap-[10px] max-[760px]:p-[10px]"><Image src="/publish-preview-reference.png" alt="Modern Apartment in Zamalek" width={317} height={181} className="h-[130px] w-[170px] rounded-[6px] object-cover object-center max-[760px]:h-[78px] max-[760px]:w-[78px]"/><div><b className="owner-label tracking-[-.01em]">Modern Apartment in Zamalek</b><p className="owner-body mt-[7px] max-[760px]:mt-[4px]">Zamalek, Cairo, Egypt</p><div className="owner-body mt-[11px] space-y-[7px] text-[#465272] max-[760px]:mt-[5px] max-[760px]:space-y-[3px]"><p className="owner-body flex items-start gap-[8px]"><Icon name="calendar" className="mt-[-1px] size-[15px] shrink-0 text-[#536083]"/><span>20 May – 25 May 2025<span className="owner-body block max-[760px]:inline"> <span className="owner-body max-[760px]:hidden">5 nights</span><span className="owner-body hidden max-[760px]:inline">(5 nights)</span></span></span></p><p className="owner-body flex items-center gap-[8px]"><Icon name="user-plain" className="size-[15px] shrink-0 text-[#536083]"/>2 Guests</p><p className="owner-body flex items-center gap-[8px] max-[760px]:hidden"><Icon name="bed" className="size-[15px] shrink-0 text-[#536083]"/>Entire apartment</p></div></div><div className="flex min-h-[106px] flex-col justify-center border-l border-[#dde2eb] pl-[25px] max-[760px]:col-span-2 max-[760px]:grid max-[760px]:min-h-0 max-[760px]:grid-cols-2 max-[760px]:border-l-0 max-[760px]:border-t max-[760px]:pt-[10px]"><span><small className="owner-helper">Total price</small><b className="owner-number-sm mt-[5px] block">EGP 13,625</b></span><span className="owner-body mt-[14px] max-[760px]:mt-0"><small className="owner-helper">You earn</small><b className="owner-number-sm mt-[5px] block">EGP 11,425</b></span></div></section>}

function GuestCard(){return <section className="mt-[14px] grid grid-cols-[1.25fr_1fr_1fr] rounded-[9px] border border-[#e7eaf1] shadow-[0_5px_18px_rgba(28,37,70,.025)] max-[760px]:block"><div className="flex items-center gap-[16px] p-[15px] max-[760px]:p-[12px]"><span className="owner-badge relative size-[72px] shrink-0 overflow-hidden rounded-full bg-white"><Image src="/omar-khaled-profile-reference.svg" alt="Omar Khaled" fill sizes="72px" className="object-cover object-center"/></span><div><div className="flex items-center"><b className="owner-label tracking-[-.01em]">Omar Khaled</b><span className="owner-badge ml-[12px] rounded-full bg-[#eee8ff] px-[9px] py-[3px]">Guest</span></div><p className="owner-body mt-[11px]">Member since April 2023</p><div className="owner-body mt-[14px] flex items-center gap-[7px]"><Icon name="star" className="size-[14px] fill-[#5824e6] text-[#5824e6]"/><span>4.9 (26 reviews)</span><span className="owner-body mx-[3px]">·</span><Icon name="shield" className="size-[14px] text-[#159447]"/><span>ID verified</span></div><Link href="/profiles/omar-khaled" className="owner-body mt-[14px] inline-flex items-center gap-[7px]">View profile<Icon name="external-link" className="size-[13px]"/></Link></div></div><div className="border-l border-[#e2e5ed] p-[15px] max-[760px]:hidden"><b className="owner-label">About Omar</b><p className="owner-body mt-[12px]">Software engineer from Alexandria.<br/>Loves to travel and explore new places.</p><div className="owner-body mt-[16px] grid grid-cols-[1fr_auto] gap-y-[12px]"><b className="owner-label">Response rate</b><span className="owner-body">100%</span><b className="owner-label">Response time</b><span className="owner-body">Within an hour</span></div></div><div className="border-l border-[#e2e5ed] p-[15px] max-[760px]:hidden"><b className="owner-label">House rules</b><div className="owner-body mt-[12px] space-y-[10px] text-[#566080]"><p className="owner-body flex items-center gap-[9px]"><Icon name="no-smoking" className="size-[14px] shrink-0"/>No smoking</p><p className="owner-body flex items-center gap-[9px]"><Icon name="party-off" className="size-[14px] shrink-0"/>No parties or events</p><p className="owner-body flex items-center gap-[9px]"><Icon name="clock" className="size-[14px] shrink-0"/>Check-in after 3:00 PM</p><p className="owner-body flex items-center gap-[9px]"><Icon name="checkout" className="size-[14px] shrink-0"/>Check-out before 11:00 AM</p></div><Link href="/owner/help-center" className="owner-body mt-[12px] inline-block">View all rules</Link></div></section>}

function Decision({decision,setDecision}:{decision:"approve"|"decline";setDecision:(v:"approve"|"decline")=>void}){return <section className="p-[15px]"><b className="owner-label">Make your decision</b><p className="owner-body mt-1 max-[760px]:hidden">You can approve or decline this booking request.</p><div className="mt-4 grid grid-cols-2 gap-[10px] max-[760px]:grid-cols-1"><Choice active={decision==="approve"} green title="Approve request" text="Accept this booking request and confirm the reservation." onClick={()=>setDecision("approve")}/><Choice active={decision==="decline"} title="Decline request" text="Decline this booking request. The guest will be notified." onClick={()=>setDecision("decline")}/></div><div className="mt-4 rounded-[8px] bg-[#F6F2FF] px-[14px] py-[12px] max-[760px]:hidden"><div className="flex items-center gap-2 text-[#11183b]"><Icon name="info-circle" className="size-[18px] shrink-0 text-[#6C4CF5]" strokeWidth={1.8}/><b className="owner-label">Need more time?</b></div><p className="owner-body ml-[26px] mt-[4px]">You have 24 hours to respond to this request. If you don&apos;t respond, the request will expire.</p></div><div className="mt-4 hidden items-center gap-2 text-[#11183b] min-[761px]:flex"><Icon name="clock" className="size-[18px] shrink-0 text-[#6C4CF5]" strokeWidth={1.8}/><b className="owner-label">Request expires in:</b><span className="owner-badge ml-[4px] rounded bg-[#f0eaff] px-3 py-2">23h : 47m : 12s</span></div></section>}
function Choice({active,green=false,title,text,onClick}:{active:boolean;green?:boolean;title:string;text:string;onClick:()=>void}){return <button onClick={onClick} className={`owner-button-text relative min-h-[125px] rounded-[7px] border p-[14px] text-left max-[760px]:flex max-[760px]:min-h-[44px] max-[760px]:items-center max-[760px]:p-[10px] ${active&&green?"border-[#4aba72] bg-[#f2fbf5]":active?"border-red-300 bg-red-50":"border-[#dde2eb]"}`}><span className={`owner-badge grid size-5 place-items-center rounded-full text-white ${green?"bg-[#159447]":"bg-red-500"}`}><Icon name={green?"check":"x"} className="size-[12px]" strokeWidth="2"/></span><b className="owner-button-text mt-4 block max-[760px]:mt-0 max-[760px]:ml-3">{title}</b><p className="owner-body mt-2 max-[760px]:hidden">{text}</p><span className={`owner-body absolute right-3 top-3 size-4 rounded-full border ${active?green?"border-[4px] border-[#159447]":"border-[4px] border-red-500":"border-[#8e98b2]"}`}/></button>}
function Message({message,setMessage}:{message:string;setMessage:(v:string)=>void}){return <section className="border-l border-[#e2e5ed] p-[15px] max-[900px]:border-l-0 max-[900px]:border-t max-[760px]:border-t-0"><b className="owner-label">Add a message (optional)</b><p className="owner-body mt-1 max-[760px]:hidden">Send a message to Omar.</p><div className="relative mt-4"><textarea value={message} maxLength={500} onChange={e=>setMessage(e.target.value)} placeholder="Write a message..." className="owner-input-text h-[105px] w-full resize-none rounded-[7px] border border-[#dfe3eb] p-3 outline-none"/><small className="owner-helper absolute bottom-3 right-3">{message.length}/500</small></div><div className="owner-body mt-3 flex flex-wrap gap-2"><button className="owner-button-text rounded-full border border-[#ded9ee] bg-[#faf8ff] px-3 py-2">Looking forward to hosting you!</button><button className="owner-button-text rounded-full border border-[#ded9ee] bg-[#faf8ff] px-3 py-2">Available if you have questions.</button><button className="owner-button-text rounded-full border border-[#ded9ee] bg-[#faf8ff] px-3 py-2">Please share your arrival time.</button></div></section>}
function BottomActions({decision,submit}:{decision:string;submit:()=>void}){return <div className="mt-[16px] flex h-[64px] items-center rounded-[8px] bg-[#f7f3ff] px-4 max-[760px]:h-auto max-[760px]:flex-col max-[760px]:gap-2 max-[760px]:bg-white max-[760px]:px-0"><span className="owner-badge grid size-9 place-items-center rounded-full bg-[#e8e0ff] max-[760px]:hidden"><Icon name="shield" className="size-5"/></span><span className="owner-body ml-3 mr-auto max-[760px]:hidden"><b className="owner-label">Secure your booking</b><p className="owner-body">Once approved, the guest will be asked to pay to confirm the booking.</p></span><button onClick={submit} className="owner-button-text h-[36px] w-[145px] rounded border border-[#9c7cff] max-[760px]:order-2 max-[760px]:w-full max-[760px]:border-red-400 max-[760px]:text-red-500">Decline request</button><button onClick={submit} className="owner-button-text ml-4 h-[36px] w-[155px] rounded bg-[#5824e6] text-white max-[760px]:ml-0 max-[760px]:w-full">{decision==="approve"?"Approve request":"Confirm decline"}</button></div>}
