"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { ChangeEvent, useEffect, useRef, useState } from "react";
import { Icon } from "@/components/host-landing/icons";
import { DarLogo } from "@/components/brand/dar-logo";
import {
 deleteDraftAsset,
 DraftAsset,
 OWNER_PROPERTY_DRAFT_KEY,
 patchOwnerPropertyDraft,
 resolveDraftAsset,
 storeDraftAsset,
 useOwnerPropertyDraft,
} from "@/lib/owner-property-draft";

type Tab = "basic"|"photos"|"amenities"|"pricing"|"policies";
type PropertyForm = { title:string; type:string; location:string; bedrooms:string; bathrooms:string; guests:string; description:string; amenities:string[]; nightlyPrice:string; minimumNights:string; cancellation:string };
const tabs:[Tab,string,string][]=[["basic","Basic Info","home"],["photos","Photos","image"],["amenities","Details & Amenities","grid-four"],["pricing","Pricing & Availability","calendar"],["policies","Policies","document-text"]];
const photos=["edit-main-reference.png","edit-kitchen-reference.png","edit-bedroom-reference.png","edit-balcony-reference.png","edit-bathroom-reference.png"];

export default function EditPropertyPage({id}:{id:string}) {
 const router=useRouter(); const search=useSearchParams(); const raw=search.get("tab"); const tab:Tab=(["basic","photos","amenities","pricing","policies"].includes(raw??"")?raw:"basic") as Tab;
 const draft=useOwnerPropertyDraft();
 const form:PropertyForm={title:draft.title,type:draft.propertyType,location:draft.address,bedrooms:draft.bedrooms,bathrooms:draft.bathrooms,guests:draft.guests,description:draft.description,amenities:draft.amenities,nightlyPrice:draft.nightlyPrice,minimumNights:draft.minimumNights,cancellation:draft.cancellationPolicy};
 useEffect(()=>{const focus=search.get("focus");if(!focus)return;const timer=window.setTimeout(()=>document.querySelector<HTMLElement>(`[data-edit-field="${CSS.escape(focus)}"]`)?.focus(),0);return()=>window.clearTimeout(timer)},[search]);
 const update=(key:keyof PropertyForm,value:string|string[])=>{const draftKey={title:"title",type:"propertyType",location:"address",bedrooms:"bedrooms",bathrooms:"bathrooms",guests:"guests",description:"description",amenities:"amenities",nightlyPrice:"nightlyPrice",minimumNights:"minimumNights",cancellation:"cancellationPolicy"}[key];patchOwnerPropertyDraft({[draftKey]:value,hasUnsubmittedChanges:true})};
 const navigateTab=(next:Tab)=>next==="pricing"?router.push(`/owner/properties/${id}/availability-rules`):router.replace(`/owner/properties/${id}/edit?tab=${next}`,{scroll:false});
 const save=(saveAsDraft=false)=>{patchOwnerPropertyDraft({status:saveAsDraft?"draft":"pending_review",hasUnsubmittedChanges:false});router.push(saveAsDraft?"/owner/properties":`/owner/properties/${id}/publish`);};
 return <div className="min-h-screen bg-[#fbfcff] pb-[66px] text-[#11183b]"><div className="owner-dashboard-content"><div className="flex items-start justify-between"><div><div className="owner-body hidden items-center gap-2 text-[var(--brand)] max-[760px]:flex"><Icon name="arrow-left" className="size-[14px]"/>Properties<Icon name="chevron" className="size-[10px] -rotate-90"/><span className="owner-body">Edit Property</span></div><h1 className="owner-page-title mt-[5px]">Edit Property</h1><p className="owner-page-description mt-[4px] max-[760px]:max-w-[245px]">Update your property details and make changes to keep your listing accurate.</p></div><span className="owner-badge mt-[15px] inline-flex items-center gap-[6px] rounded-[5px] bg-[#eaf8ed] px-[11px] py-[7px]"><Icon name="check-circle" className="size-[13px]"/>Published</span></div><TabBar tab={tab} onChange={navigateTab}/><div className="mt-5">{tab==="basic"?<BasicLayout form={form} update={update}/>:tab==="photos"?<PhotosCard expanded/>:tab==="amenities"?<Amenities form={form} update={update} expanded/>:tab==="pricing"?<Pricing form={form} update={update}/>:<Policies form={form} update={update}/>}</div></div><Actions onDiscard={()=>router.back()} onDraft={()=>save(true)} onSave={()=>save(false)}/></div>;
}

function DesktopHeader({id}:{id:string}){return <header className="flex h-[58px] items-center justify-between border-b border-[#edf0f6] px-[22px] max-[760px]:hidden"><div className="owner-body flex gap-[13px] text-[#68718e]"><Link href="/owner/properties">Properties</Link><Icon name="chevron" className="size-[10px] -rotate-90"/><span className="owner-body">Edit Property</span></div><div className="flex gap-[10px]"><Link href={`/owner/properties/${id}/publish`} className="owner-button-text flex h-[34px] items-center gap-[8px] rounded-[5px] border border-[#dce1eb] px-[13px]"><Icon name="message" className="size-[14px]"/>Preview listing <Icon name="arrow-right" className="size-[13px] -rotate-45"/></Link><button aria-label="More options" className="owner-button-text grid size-[34px] place-items-center rounded-[5px] border border-[#dce1eb]"><Icon name="more-horizontal" className="size-[16px]"/></button></div></header>}
function MobileHeader(){return <header className="hidden h-[61px] items-center justify-between border-b border-[#edf0f6] px-[16px] max-[760px]:flex"><Icon name="menu" className="size-[20px]"/><DarLogo surface="light" alt="DAR" width={86} height={36} className="h-[34px] w-[86px] object-contain"/><Icon name="bell" className="size-[18px]"/></header>}
function TabBar({tab,onChange}:{tab:Tab;onChange:(v:Tab)=>void}){return <nav className="mt-[18px] grid h-[48px] grid-cols-5 rounded-[8px] border border-[#e8ebf2] px-[14px] max-[760px]:h-[65px] max-[760px]:px-0">{tabs.map(([key,label,icon])=><button onClick={()=>onChange(key)} key={key} className={`owner-button-text relative flex items-center justify-center gap-[8px] ${tab===key?"text-[var(--brand)]":"text-[#5b6483]"} max-[760px]:flex-col max-[760px]:gap-[4px]`}><Icon name={icon} className="size-[15px] max-[760px]:size-[16px]"/><span className="owner-body max-[760px]:hidden">{label}</span><span className="owner-body hidden max-[760px]:inline">{key==="amenities"?"Details":key.charAt(0).toUpperCase()+key.slice(1)}</span>{tab===key?<i className="absolute inset-x-[7px] bottom-0 h-[2px] rounded bg-[var(--brand)]"/>:null}</button>)}</nav>}
function BasicLayout({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <><div className="grid grid-cols-2 gap-[14px] max-[920px]:grid-cols-1"><BasicInfo form={form} update={update}/><PhotosCard/></div><Amenities form={form} update={update}/></>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`rounded-[9px] border border-[#e8ebf2] bg-white p-[15px] ${className}`}>{children}</section>}
function BasicInfo({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <Card><h2 className="owner-section-title">Basic Information</h2><div className="mt-[14px] space-y-[12px]"><Field label="Property Title" value={form.title} onChange={v=>update("title",v)} count={`${form.title.length}/100`}/><Select label="Property Type" value={form.type} onChange={v=>update("type",v)} options={["Apartment","Villa","Studio"]}/><Field label="Location" value={form.location} onChange={v=>update("location",v)} icon="location" fieldName="location"/><div className="grid grid-cols-3 gap-[12px]"><Select label="Bedrooms" value={form.bedrooms} onChange={v=>update("bedrooms",v)} options={["1","2","3","4"]}/><Select label="Bathrooms" value={form.bathrooms} onChange={v=>update("bathrooms",v)} options={["1","2","3"]}/><Select label="Guests" value={form.guests} onChange={v=>update("guests",v)} options={["2","4","6","8"]}/></div><label className="owner-label block">Short Description<div className="relative mt-[6px]"><textarea data-edit-field="description" value={form.description} onChange={e=>update("description",e.target.value)} className="owner-input-text h-[63px] w-full resize-none rounded-[6px] border border-[#dce1eb] px-[10px] py-[8px] outline-none focus:border-[#8d68ff] focus-visible:ring-2 focus-visible:ring-[var(--brand)]"/><span className="owner-body absolute bottom-[7px] right-[8px]">{form.description.length}/500</span></div></label></div><Tip/></Card>}
function Field({label,value,onChange,count,icon,fieldName}:{label:string;value:string;onChange:(v:string)=>void;count?:string;icon?:string;fieldName?:string}){return <label className="owner-label block">{label}<div className="relative mt-[6px]">{icon?<Icon name={icon} className="absolute left-[10px] top-[10px] size-[13px]"/>:null}<input data-edit-field={fieldName} value={value} onChange={e=>onChange(e.target.value)} className={`owner-input-text h-[35px] w-full rounded-[6px] border border-[#dce1eb] outline-none focus:border-[#8d68ff] ${icon?"pl-[31px]":"pl-[10px]"}`}/>{count?<span className="owner-body absolute right-[9px] top-[10px]">{count}</span>:null}</div></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="owner-label block">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="owner-input-text mt-[6px] h-[35px] w-full rounded-[6px] border border-[#dce1eb] bg-white px-[9px] outline-none">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Tip(){return <div className="mt-[14px] flex min-h-[52px] items-center gap-[12px] rounded-[6px] bg-[#f8f6ff] px-[13px]"><Icon name="bulb" className="size-[21px] shrink-0 text-[#6332ee]" strokeWidth="1.8"/><div><b className="owner-label">Tips for a great listing</b><p className="owner-body mt-[4px]">A clear title, great photos, and a detailed description help you get more bookings.</p></div></div>}
function PhotosCard({expanded=false}:{expanded?:boolean}){
 const draft=useOwnerPropertyDraft();
 const inputRef=useRef<HTMLInputElement>(null);
 const [uploading,setUploading]=useState(false);
 const [feedback,setFeedback]=useState<{kind:"success"|"error";text:string}|null>(null);
 useEffect(()=>{window.dispatchEvent(new StorageEvent("storage",{key:OWNER_PROPERTY_DRAFT_KEY}))},[]);
 const uploadedPhotos=draft.photos.filter(photo=>!photo.builtInUrl&&!photo.id.startsWith("builtin-"));
 const photoCount=photos.length+uploadedPhotos.length;

 async function addPhotos(event:ChangeEvent<HTMLInputElement>){
  const selected=Array.from(event.target.files??[]);
  event.target.value="";
  if(!selected.length||uploading)return;
  const available=20-photoCount;
  if(available<=0){setFeedback({kind:"error",text:"You can add up to 20 photos."});return;}
  const allowedTypes=new Set(["image/jpeg","image/png","image/webp"]);
  const errors:string[]=[];
  const valid:File[]=[];
  for(const file of selected){
   if(!allowedTypes.has(file.type)){errors.push(`${file.name}: unsupported file type.`);continue;}
   if(file.size>10*1024*1024){errors.push(`${file.name}: file is larger than 10 MB.`);continue;}
   valid.push(file);
  }
  if(valid.length>available){errors.push(`Only ${available} more photo${available===1?"":"s"} can be added (20 maximum).`);valid.splice(available);}
  if(!valid.length){setFeedback({kind:"error",text:errors.join(" ")||"No valid photos were selected."});return;}
  setUploading(true);
  const stored:DraftAsset[]=[];
  try{
   for(const file of valid)stored.push(await storeDraftAsset(file));
   const saved=patchOwnerPropertyDraft({photos:[...draft.photos,...stored],hasUnsubmittedChanges:true});
   if(!saved)throw new Error("metadata-storage-failed");
   setFeedback(errors.length?{kind:"error",text:`${stored.length} photo${stored.length===1?"":"s"} added. ${errors.join(" ")}`}:{kind:"success",text:`${stored.length} photo${stored.length===1?"":"s"} added successfully.`});
  }catch{
   await Promise.all(stored.map(asset=>deleteDraftAsset(asset.id)));
   setFeedback({kind:"error",text:"The photos could not be stored. Please try again."});
  }finally{setUploading(false);}
 }

 const addButtonClass="owner-button-text grid place-items-center rounded-[6px] border border-dashed border-[#a98cff] transition-colors hover:bg-[var(--brand-soft)] active:bg-[var(--surface-muted)] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--brand)] focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50";
 return <Card className={expanded?"mx-auto max-w-[760px]":""}><div className="flex justify-between"><h2 className="owner-section-title">Property Photos</h2><span className="owner-body">{photoCount}/20 photos</span></div><input ref={inputRef} className="sr-only" type="file" accept=".jpg,.jpeg,.png,.webp,image/jpeg,image/png,image/webp" multiple disabled={uploading||photoCount>=20} onChange={event=>void addPhotos(event)}/><div className="mt-[14px] grid h-[322px] grid-cols-[1fr_1fr_.82fr] grid-rows-[1fr_1fr_1.08fr] gap-[8px] max-[760px]:hidden"><Photo src={photos[0]} className="col-span-2 row-span-2" position="object-center"/><Photo src={photos[1]} position="object-center"/><Photo src={photos[2]} position="object-center"/><Photo src={photos[3]} position="object-center"/><Photo src={photos[4]} position="object-center"/>{uploadedPhotos.map(photo=><UploadedPhoto key={photo.id} photo={photo}/>)}<button type="button" disabled={uploading||photoCount>=20} aria-label={uploading?"Adding photos":"Add photos"} aria-busy={uploading} onClick={()=>inputRef.current?.click()} className={addButtonClass}><span className="inline-flex items-center gap-1"><Icon name="plus" className="size-[13px]"/>{uploading?"Adding…":"Add"}</span><br/>Photos</button></div><div className="mt-[12px] hidden grid-cols-4 gap-[7px] max-[760px]:grid">{photos.map(p=><Photo key={p} src={p} className="aspect-square" position="object-center"/>)}{uploadedPhotos.map(photo=><UploadedPhoto key={photo.id} photo={photo} className="aspect-square"/>)}<button type="button" disabled={uploading||photoCount>=20} aria-label={uploading?"Adding photo":"Add photo"} aria-busy={uploading} onClick={()=>inputRef.current?.click()} className={`${addButtonClass} aspect-square`}><Icon name="plus" className="size-[14px]"/></button></div>{feedback?<p role={feedback.kind==="error"?"alert":"status"} className={`owner-body mt-[10px] rounded-[6px] border px-[10px] py-[8px] ${feedback.kind==="error"?"border-danger/30 bg-danger/10 text-danger":"border-success/30 bg-success/10 text-success"}`}>{feedback.text}</p>:null}<p className="owner-body mt-[12px] max-[760px]:hidden">Drag and drop photos to reorder</p><p className="owner-body mt-[8px] flex items-center gap-[7px] max-[760px]:hidden"><Icon name="info-circle" className="size-[14px]"/>JPG, PNG or WEBP. Max size 10MB per photo.</p><div className="hidden max-[760px]:block"><Tip/></div></Card>
}
function Photo({src,className="",position="object-center"}:{src:string;className?:string;position?:string}){return <div className={`relative min-h-0 overflow-hidden rounded-[6px] ${className}`}><Image src={`/${src}`} alt="" fill className={`object-cover ${position}`} sizes="300px"/></div>}
function UploadedPhoto({photo,className=""}:{photo:DraftAsset;className?:string}){const [src,setSrc]=useState("/property-studio-reference.png");useEffect(()=>{let active=true;let created="";void resolveDraftAsset(photo).then(url=>{created=url;if(active)setSrc(url)});return()=>{active=false;if(created.startsWith("blob:"))URL.revokeObjectURL(created)}},[photo]);return <div className={`relative min-h-0 overflow-hidden rounded-[6px] bg-[var(--surface-muted)] ${className}`}><Image src={src} alt={photo.name} fill unoptimized={src.startsWith("blob:")} className="object-cover" sizes="300px"/></div>}
const allAmenities=["Wi-Fi","Air Conditioning","Kitchen","Washer","TV","Pool","Free Parking"];
function Amenities({form,update,expanded=false}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void;expanded?:boolean}){return <Card className={`mt-[14px] ${expanded?"mx-auto max-w-[900px]":""}`}><h2 className="owner-section-title">Details &amp; Amenities</h2><p className="owner-body mt-[13px]">Amenities</p><div className="mt-[7px] flex flex-nowrap items-center gap-[10px] overflow-x-auto max-[760px]:grid max-[760px]:grid-cols-2 max-[760px]:overflow-visible">{allAmenities.map(a=>{const checked=form.amenities.some(x=>x.toLowerCase()===a.toLowerCase());return <button type="button" aria-pressed={checked} key={a} onClick={()=>update("amenities",checked?form.amenities.filter(x=>x.toLowerCase()!==a.toLowerCase()):[...form.amenities,a])} className="owner-button-text inline-flex h-[38px] w-fit min-w-[76px] shrink-0 items-center justify-start gap-[8px] whitespace-nowrap rounded-[6px] border border-[#e0e4ed] px-[11px] text-[#303957] transition hover:shadow-[var(--shadow-card-hover)] active:bg-[var(--brand-soft)] focus-visible:outline-none focus-visible:shadow-[var(--shadow-focus)] max-[760px]:w-full"><span className={`owner-badge grid size-[14px] shrink-0 place-items-center rounded-[2px] border ${checked?"border-[var(--brand)] bg-[var(--brand)] text-white":"border-[#9aa3b8] bg-white"}`}>{checked?<Icon name="check" className="size-[9px]" strokeWidth="2.5"/>:null}</span><span className="owner-body whitespace-nowrap">{a}</span></button>})}</div></Card>}
function Pricing({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <Card className="mx-auto max-w-[720px]"><h2 className="owner-section-title">Pricing &amp; Availability</h2><div className="mt-4 grid grid-cols-2 gap-4"><Field label="Nightly price (EGP)" value={form.nightlyPrice} onChange={v=>update("nightlyPrice",v)}/><Select label="Minimum nights" value={form.minimumNights} onChange={v=>update("minimumNights",v)} options={["1","2","3","7"]}/></div></Card>}
function Policies({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <Card className="mx-auto max-w-[720px]"><h2 className="owner-section-title">Policies</h2><div className="mt-4"><Select label="Cancellation policy" value={form.cancellation} onChange={v=>update("cancellation",v)} options={["Flexible","Moderate","Strict"]}/></div></Card>}
function Actions({onDiscard,onDraft,onSave}:{onDiscard:()=>void;onDraft:()=>void;onSave:()=>void}){return <div className="mx-8 mb-8 mt-3 flex min-h-[62px] items-center rounded-lg border border-[#e7eaf2] bg-white px-5 max-[760px]:mx-3 max-[760px]:mb-5 max-[760px]:h-auto max-[760px]:flex-col max-[760px]:gap-[8px] max-[760px]:border-0 max-[760px]:px-0"><button onClick={onDiscard} className="owner-button-text h-[38px] w-[138px] rounded-[5px] border border-[#d8deea] max-[760px]:order-3 max-[760px]:h-[42px] max-[760px]:w-full">Discard Changes</button><div className="ml-auto flex gap-[12px] max-[760px]:ml-0 max-[760px]:w-full max-[760px]:flex-col"><button onClick={onDraft} className="owner-button-text h-[38px] w-[132px] rounded-[5px] border border-[#9d7cff] max-[760px]:h-[42px] max-[760px]:w-full">Save as Draft</button><button onClick={onSave} className="owner-button-text h-[38px] w-[174px] rounded-[5px] bg-[#5824e6] text-white max-[760px]:h-[42px] max-[760px]:w-full">Save Changes</button></div></div>}
