"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { Icon } from "@/components/host-landing/icons";
import { DarLogo } from "@/components/brand/dar-logo";
import { ownerNavHref, ownerRoutes } from "@/lib/owner-routes";

type Tab = "basic"|"photos"|"amenities"|"pricing"|"policies";
type PropertyForm = { title:string; type:string; location:string; bedrooms:string; bathrooms:string; guests:string; description:string; amenities:string[]; nightlyPrice:string; minimumNights:string; cancellation:string };
const initial:PropertyForm={title:"Modern Apartment in Zamalek",type:"Apartment",location:"Zamalek, Cairo, Egypt",bedrooms:"2",bathrooms:"2",guests:"4",description:"A stylish and modern apartment in the heart of Zamalek. Close to the Nile, cafes, and top attractions.",amenities:["Wi-Fi","Air Conditioning","Kitchen"],nightlyPrice:"2500",minimumNights:"2",cancellation:"Flexible"};
const tabs:[Tab,string,string][]=[["basic","Basic Info","home"],["photos","Photos","image"],["amenities","Details & Amenities","grid-four"],["pricing","Pricing & Availability","calendar"],["policies","Policies","document-text"]];
const photos=["property-studio-sharp.png","add-property-thumb-kitchen.png","add-property-thumb-bedroom.png","add-property-thumb-balcony.png","add-property-thumb-bathroom.png"];

export default function EditPropertyPage({id}:{id:string}) {
 const router=useRouter(); const search=useSearchParams(); const raw=search.get("tab"); const tab:Tab=(["basic","photos","amenities","pricing","policies"].includes(raw??"")?raw:"basic") as Tab;
 const [form,setForm]=useState<PropertyForm>(initial);
 useEffect(()=>{let active=true;queueMicrotask(()=>{if(!active)return;try{const saved=localStorage.getItem(`dar-owner-property:${id}`);if(saved)setForm({...initial,...JSON.parse(saved)});}catch{}});return()=>{active=false}},[id]);
 const update=(key:keyof PropertyForm,value:string|string[])=>setForm(v=>({...v,[key]:value}));
 const navigateTab=(next:Tab)=>next==="pricing"?router.push(`/owner/properties/${id}/availability-rules`):router.replace(`/owner/properties/${id}/edit?tab=${next}`,{scroll:false});
 const save=(draft=false)=>{localStorage.setItem(`dar-owner-property:${id}`,JSON.stringify(form));localStorage.setItem(`dar-owner-property-status:${id}`,draft?"draft":"pending_review");router.push(draft?"/owner/properties":`/owner/properties/${id}/publish`);};
 return <main className="min-h-screen bg-[#fbfcff] text-[#11183b]"><div className="owner-dashboard-frame overflow-hidden"><Sidebar/><section className="owner-dashboard-main pb-[66px]"><DesktopHeader id={id}/><MobileHeader/><div className="owner-dashboard-content"><div className="flex items-start justify-between"><div><div className="owner-body hidden items-center gap-2 text-[#5b2be0] max-[760px]:flex"><Icon name="arrow-left" className="size-[14px]"/>Properties<Icon name="chevron" className="size-[10px] -rotate-90"/><span className="owner-body">Edit Property</span></div><h1 className="owner-page-title mt-[5px]">Edit Property</h1><p className="owner-page-description mt-[4px] max-[760px]:max-w-[245px]">Update your property details and make changes to keep your listing accurate.</p></div><span className="owner-badge mt-[15px] inline-flex items-center gap-[6px] rounded-[5px] bg-[#eaf8ed] px-[11px] py-[7px]"><Icon name="check-circle" className="size-[13px]"/>Published</span></div><TabBar tab={tab} onChange={navigateTab}/><div className="mt-5">{tab==="basic"?<BasicLayout form={form} update={update}/>:tab==="photos"?<PhotosCard expanded/>:tab==="amenities"?<Amenities form={form} update={update} expanded/>:tab==="pricing"?<Pricing form={form} update={update}/>:<Policies form={form} update={update}/>}</div></div><Actions onDiscard={()=>router.back()} onDraft={()=>save(true)} onSave={()=>save(false)}/></section></div></main>;
}

function Sidebar(){const items=[["Dashboard","dashboard"],["Properties","properties"],["Bookings","bookings"],["Calendar","calendar"],["Messages","messages"],["Reviews","reviews"],["Analytics","analytics"],["Payouts","payouts"],["Settings","settings"]] as const;return <aside className="sticky top-[8px] flex h-[calc(100vh-16px)] min-h-[calc(100vh-16px)] w-[205px] shrink-0 self-start flex-col border-r border-[#edf0f6] bg-white px-[14px] pb-[14px] pt-[16px] max-[760px]:hidden"><DarLogo surface="light" alt="DAR Stay Different" width={105} height={54} className="ml-[7px] h-[48px] w-[105px] object-contain object-left"/><nav className="mt-[22px] min-h-0 flex-1 space-y-[4px]">{items.map(([label,icon],i)=><Link key={label} href={ownerNavHref(label)} className={`owner-button-text flex h-[40px] items-center gap-[13px] rounded-[7px] px-[10px] transition-colors ${i===1?"bg-[#f5f0ff] text-[#5b2be0]":"text-[#535d80] hover:bg-[#faf8ff] hover:text-[#5b2be0]"}`}><EditNavIcon name={icon}/>{label}</Link>)}</nav><div className="mt-auto flex w-full shrink-0 flex-col gap-[12px]"><Link href={ownerRoutes.publicProfile()} className="owner-button-text flex h-[50px] w-full items-center gap-[10px] rounded-[7px] border border-[#e3e7ef] bg-white px-[9px] text-left shadow-[0_4px_14px_rgba(25,34,68,.025)]"><Image src="/owner-selfie-ahmed-reference.png" alt="Ahmed Hassan" width={30} height={30} className="size-[30px] rounded-full object-cover" quality={90}/><span className="owner-body min-w-0 flex-1"><b className="owner-button-text block">Ahmed Hassan</b><small className="owner-helper mt-[2px] block">Host</small></span><Icon name="chevron" className="size-[11px] shrink-0 text-[#596381]"/></Link><Link href={ownerRoutes.help} className="owner-button-text flex h-[46px] w-full items-center gap-[10px] rounded-[7px] border border-[#e3e7ef] bg-white px-[10px] shadow-[0_4px_14px_rgba(25,34,68,.02)]"><svg aria-hidden="true" className="size-[16px] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.3 2.3 0 1 1 3.1 2.2c-.9.4-1.4 1-1.4 1.8v.4M12 17h.01"/></svg>Help Center</Link></div></aside>}

function EditNavIcon({name}:{name:"dashboard"|"properties"|"bookings"|"calendar"|"messages"|"reviews"|"analytics"|"payouts"|"settings"}){return <svg aria-hidden="true" className="size-[19px] shrink-0" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round">{name==="dashboard"&&<><path d="m4 11 8-7 8 7"/><path d="M6.5 9.5V20h11V9.5M10 20v-6h4v6"/></>}{name==="properties"&&<><path d="m3.5 10.5 8.5-7 8.5 7"/><path d="M5.5 9v11h13V9"/><rect x="9" y="12" width="6" height="8" rx="1"/></>}{name==="bookings"&&<><rect x="3.5" y="5.5" width="17" height="15" rx="2"/><path d="M7.5 3.5v4M16.5 3.5v4M3.5 10h17M7 14h3M7 17h3"/></>}{name==="calendar"&&<><rect x="3.5" y="5.5" width="17" height="15" rx="2"/><path d="M7.5 3.5v4M16.5 3.5v4M3.5 10h17M8 14h.01M12 14h.01M16 14h.01M8 17h.01M12 17h.01"/></>}{name==="messages"&&<path d="M4 5.5h16v11H9l-5 3v-14Z"/>}{name==="reviews"&&<><path d="M4 5.5h16v11H9l-5 3v-14Z"/><path d="m12 8 1 2 2.2.3-1.6 1.5.4 2.2-2-1-2 1 .4-2.2-1.6-1.5 2.2-.3 1-2Z"/></>}{name==="analytics"&&<><path d="M4 20v-5h4v5M10 20V9h4v11M16 20V4h4v16M3 20h18"/><path d="m5 11 5-5 4 3 5-6"/></>}{name==="payouts"&&<><rect x="3.5" y="6" width="17" height="13" rx="2"/><path d="M3.5 10h17M16 13h4v3h-4a1.5 1.5 0 0 1 0-3Z"/></>}{name==="settings"&&<><circle cx="12" cy="12" r="3"/><path d="M19 13.5v-3l-2-.7-.7-1.7.9-1.9-2.1-2.1-1.9.9-1.7-.7-.7-2.1h-3L8.1 4l-1.9-.9-2.1 2.1L5 7.1l-.7 1.7-2 .7v3l2 .7.7 1.7-.9 1.9 2.1 2.1 1.9-.9 1.7.7.7 2.1h3l.7-2.1 1.7-.7 1.9.9 2.1-2.1-.9-1.9.7-1.7 2-.7Z"/></>}</svg>}
function DesktopHeader({id}:{id:string}){return <header className="flex h-[58px] items-center justify-between border-b border-[#edf0f6] px-[22px] max-[760px]:hidden"><div className="owner-body flex gap-[13px] text-[#68718e]"><Link href="/owner/properties">Properties</Link><Icon name="chevron" className="size-[10px] -rotate-90"/><span className="owner-body">Edit Property</span></div><div className="flex gap-[10px]"><Link href={`/owner/properties/${id}/publish`} className="owner-button-text flex h-[34px] items-center gap-[8px] rounded-[5px] border border-[#dce1eb] px-[13px]"><Icon name="message" className="size-[14px]"/>Preview listing <Icon name="arrow-right" className="size-[13px] -rotate-45"/></Link><button aria-label="More options" className="owner-button-text grid size-[34px] place-items-center rounded-[5px] border border-[#dce1eb]"><Icon name="more-horizontal" className="size-[16px]"/></button></div></header>}
function MobileHeader(){return <header className="hidden h-[61px] items-center justify-between border-b border-[#edf0f6] px-[16px] max-[760px]:flex"><Icon name="menu" className="size-[20px]"/><DarLogo surface="light" alt="DAR" width={86} height={36} className="h-[34px] w-[86px] object-contain"/><Icon name="bell" className="size-[18px]"/></header>}
function TabBar({tab,onChange}:{tab:Tab;onChange:(v:Tab)=>void}){return <nav className="mt-[18px] grid h-[48px] grid-cols-5 rounded-[8px] border border-[#e8ebf2] px-[14px] max-[760px]:h-[65px] max-[760px]:px-0">{tabs.map(([key,label,icon])=><button onClick={()=>onChange(key)} key={key} className={`owner-button-text relative flex items-center justify-center gap-[8px] ${tab===key?"text-[#5b2be0]":"text-[#5b6483]"} max-[760px]:flex-col max-[760px]:gap-[4px]`}><Icon name={icon} className="size-[15px] max-[760px]:size-[16px]"/><span className="owner-body max-[760px]:hidden">{label}</span><span className="owner-body hidden max-[760px]:inline">{key==="amenities"?"Details":key.charAt(0).toUpperCase()+key.slice(1)}</span>{tab===key?<i className="absolute inset-x-[7px] bottom-0 h-[2px] rounded bg-[#5b2be0]"/>:null}</button>)}</nav>}
function BasicLayout({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <><div className="grid grid-cols-2 gap-[14px] max-[920px]:grid-cols-1"><BasicInfo form={form} update={update}/><PhotosCard/></div><Amenities form={form} update={update}/></>}
function Card({children,className=""}:{children:React.ReactNode;className?:string}){return <section className={`rounded-[9px] border border-[#e8ebf2] bg-white p-[15px] ${className}`}>{children}</section>}
function BasicInfo({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <Card><h2 className="owner-section-title">Basic Information</h2><div className="mt-[14px] space-y-[12px]"><Field label="Property Title" value={form.title} onChange={v=>update("title",v)} count={`${form.title.length}/100`}/><Select label="Property Type" value={form.type} onChange={v=>update("type",v)} options={["Apartment","Villa","Studio"]}/><Field label="Location" value={form.location} onChange={v=>update("location",v)} icon="location"/><div className="grid grid-cols-3 gap-[12px]"><Select label="Bedrooms" value={form.bedrooms} onChange={v=>update("bedrooms",v)} options={["1","2","3","4"]}/><Select label="Bathrooms" value={form.bathrooms} onChange={v=>update("bathrooms",v)} options={["1","2","3"]}/><Select label="Guests" value={form.guests} onChange={v=>update("guests",v)} options={["2","4","6","8"]}/></div><label className="owner-label block">Short Description<div className="relative mt-[6px]"><textarea value={form.description} onChange={e=>update("description",e.target.value)} className="owner-input-text h-[63px] w-full resize-none rounded-[6px] border border-[#dce1eb] px-[10px] py-[8px] outline-none focus:border-[#8d68ff]"/><span className="owner-body absolute bottom-[7px] right-[8px]">{form.description.length}/500</span></div></label></div><Tip/></Card>}
function Field({label,value,onChange,count,icon}:{label:string;value:string;onChange:(v:string)=>void;count?:string;icon?:string}){return <label className="owner-label block">{label}<div className="relative mt-[6px]">{icon?<Icon name={icon} className="absolute left-[10px] top-[10px] size-[13px]"/>:null}<input value={value} onChange={e=>onChange(e.target.value)} className={`owner-input-text h-[35px] w-full rounded-[6px] border border-[#dce1eb] outline-none focus:border-[#8d68ff] ${icon?"pl-[31px]":"pl-[10px]"}`}/>{count?<span className="owner-body absolute right-[9px] top-[10px]">{count}</span>:null}</div></label>}
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:string[]}){return <label className="owner-label block">{label}<select value={value} onChange={e=>onChange(e.target.value)} className="owner-input-text mt-[6px] h-[35px] w-full rounded-[6px] border border-[#dce1eb] bg-white px-[9px] outline-none">{options.map(o=><option key={o}>{o}</option>)}</select></label>}
function Tip(){return <div className="mt-[14px] flex min-h-[52px] items-center gap-[12px] rounded-[6px] bg-[#f8f6ff] px-[13px]"><Icon name="bulb" className="size-[21px] shrink-0 text-[#6332ee]" strokeWidth="1.8"/><div><b className="owner-label">Tips for a great listing</b><p className="owner-body mt-[4px]">A clear title, great photos, and a detailed description help you get more bookings.</p></div></div>}
function PhotosCard({expanded=false}:{expanded?:boolean}){return <Card className={expanded?"mx-auto max-w-[760px]":""}><div className="flex justify-between"><h2 className="owner-section-title">Property Photos</h2><span className="owner-body">7/20 photos</span></div><div className="mt-[14px] grid h-[322px] grid-cols-[1fr_1fr_.82fr] grid-rows-[1fr_1fr_1.08fr] gap-[8px] max-[760px]:hidden"><Photo src={photos[0]} className="col-span-2 row-span-2" position="object-center"/><Photo src={photos[1]} position="object-center"/><Photo src={photos[2]} position="object-center"/><Photo src={photos[3]} position="object-center"/><Photo src={photos[4]} position="object-center"/><button className="owner-button-text grid place-items-center rounded-[6px] border border-dashed border-[#a98cff]"><span className="inline-flex items-center gap-1"><Icon name="plus" className="size-[13px]"/>Add</span><br/>Photos</button></div><div className="mt-[12px] hidden grid-cols-4 gap-[7px] max-[760px]:grid">{photos.slice(0,3).map(p=><Photo key={p} src={p} className="aspect-square" position="object-center"/>)}<button aria-label="Add photo" className="owner-button-text grid aspect-square place-items-center rounded-[6px] border border-dashed border-[#a98cff]"><Icon name="plus" className="size-[14px]"/></button></div><p className="owner-body mt-[12px] max-[760px]:hidden">Drag and drop photos to reorder</p><p className="owner-body mt-[8px] flex items-center gap-[7px] max-[760px]:hidden"><Icon name="info-circle" className="size-[14px]"/>JPG, PNG or WEBP. Max size 10MB per photo.</p><div className="hidden max-[760px]:block"><Tip/></div></Card>}
function Photo({src,className="",position="object-center"}:{src:string;className?:string;position?:string}){return <div className={`relative min-h-0 overflow-hidden rounded-[6px] ${className}`}><Image src={`/${src}`} alt="" fill className={`object-cover ${position}`} sizes="(max-width: 760px) 34vw, (max-width: 1200px) 42vw, 560px" quality={90}/></div>}
const allAmenities=["Wi-Fi","Air Conditioning","Kitchen","Washer","TV","Pool","Free Parking"];
function Amenities({form,update,expanded=false}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void;expanded?:boolean}){return <Card className={`mt-[14px] ${expanded?"mx-auto max-w-[900px]":""}`}><h2 className="owner-section-title">Details &amp; Amenities</h2><p className="owner-body mt-[13px]">Amenities</p><div className="mt-[7px] flex flex-nowrap items-center gap-[10px] overflow-x-auto max-[760px]:grid max-[760px]:grid-cols-2 max-[760px]:overflow-visible">{allAmenities.map(a=>{const checked=form.amenities.includes(a);return <button key={a} onClick={()=>update("amenities",checked?form.amenities.filter(x=>x!==a):[...form.amenities,a])} className="owner-button-text inline-flex h-[38px] w-fit min-w-[76px] shrink-0 items-center justify-start gap-[8px] whitespace-nowrap rounded-[6px] border border-[#e0e4ed] px-[11px] text-[#303957] max-[760px]:w-full"><span className={`owner-badge grid size-[14px] shrink-0 place-items-center rounded-[2px] border ${checked?"border-[#5b2be0] bg-[#5b2be0] text-white":"border-[#9aa3b8] bg-white"}`}>{checked?<Icon name="check" className="size-[9px]" strokeWidth="2.5"/>:null}</span><span className="owner-body whitespace-nowrap">{a}</span></button>})}</div></Card>}
function Pricing({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <Card className="mx-auto max-w-[720px]"><h2 className="owner-section-title">Pricing &amp; Availability</h2><div className="mt-4 grid grid-cols-2 gap-4"><Field label="Nightly price (EGP)" value={form.nightlyPrice} onChange={v=>update("nightlyPrice",v)}/><Select label="Minimum nights" value={form.minimumNights} onChange={v=>update("minimumNights",v)} options={["1","2","3","7"]}/></div></Card>}
function Policies({form,update}:{form:PropertyForm;update:(k:keyof PropertyForm,v:string|string[])=>void}){return <Card className="mx-auto max-w-[720px]"><h2 className="owner-section-title">Policies</h2><div className="mt-4"><Select label="Cancellation policy" value={form.cancellation} onChange={v=>update("cancellation",v)} options={["Flexible","Moderate","Strict"]}/></div></Card>}
function Actions({onDiscard,onDraft,onSave}:{onDiscard:()=>void;onDraft:()=>void;onSave:()=>void}){return <div className="mx-8 mb-8 mt-3 flex min-h-[62px] items-center rounded-lg border border-[#e7eaf2] bg-white px-5 max-[760px]:mx-3 max-[760px]:mb-5 max-[760px]:h-auto max-[760px]:flex-col max-[760px]:gap-[8px] max-[760px]:border-0 max-[760px]:px-0"><button onClick={onDiscard} className="owner-button-text h-[38px] w-[138px] rounded-[5px] border border-[#d8deea] max-[760px]:order-3 max-[760px]:h-[42px] max-[760px]:w-full">Discard Changes</button><div className="ml-auto flex gap-[12px] max-[760px]:ml-0 max-[760px]:w-full max-[760px]:flex-col"><button onClick={onDraft} className="owner-button-text h-[38px] w-[132px] rounded-[5px] border border-[#9d7cff] max-[760px]:h-[42px] max-[760px]:w-full">Save as Draft</button><button onClick={onSave} className="owner-button-text h-[38px] w-[174px] rounded-[5px] bg-[#5824e6] text-white max-[760px]:h-[42px] max-[760px]:w-full">Save Changes</button></div></div>}
