// Generated by Supabase CLI from the local DAR public schema.
// Command: npx supabase gen types typescript --local --schema public
// Manual edits will be overwritten.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      audit_logs: {
        Row: {
          action_type: Database["public"]["Enums"]["audit_action_type"]
          actor_profile_id: string | null
          actor_type: Database["public"]["Enums"]["audit_actor_type"]
          after_state: Json | null
          before_state: Json | null
          created_at: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["audit_entity_type"]
          id: string
          ip_address: unknown
          summary: string
          user_agent: string | null
        }
        Insert: {
          action_type: Database["public"]["Enums"]["audit_action_type"]
          actor_profile_id?: string | null
          actor_type?: Database["public"]["Enums"]["audit_actor_type"]
          after_state?: Json | null
          before_state?: Json | null
          created_at?: string
          entity_id: string
          entity_type: Database["public"]["Enums"]["audit_entity_type"]
          id?: string
          ip_address?: unknown
          summary: string
          user_agent?: string | null
        }
        Update: {
          action_type?: Database["public"]["Enums"]["audit_action_type"]
          actor_profile_id?: string | null
          actor_type?: Database["public"]["Enums"]["audit_actor_type"]
          after_state?: Json | null
          before_state?: Json | null
          created_at?: string
          entity_id?: string
          entity_type?: Database["public"]["Enums"]["audit_entity_type"]
          id?: string
          ip_address?: unknown
          summary?: string
          user_agent?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      bookings: {
        Row: {
          booking_reference: string
          cancellation_reason: string | null
          cancelled_at: string | null
          check_in_date: string
          check_out_date: string
          cleaning_fee_amount: number
          completed_at: string | null
          confirmed_at: string | null
          created_at: string
          currency_code: string
          discount_amount: number
          expired_at: string | null
          guests_count: number
          id: string
          nightly_amount: number
          owner_actioned_at: string | null
          owner_id: string
          owner_response_message: string | null
          payment_reference: string | null
          payment_status: Database["public"]["Enums"]["booking_payment_status"]
          payment_submitted_at: string | null
          property_id: string
          refunded_at: string | null
          requested_at: string
          service_fee_amount: number
          special_requests: string | null
          status: Database["public"]["Enums"]["booking_status"]
          subtotal_amount: number
          total_amount: number
          traveler_email: string | null
          traveler_full_name: string | null
          traveler_id: string
          traveler_phone: string | null
          updated_at: string
        }
        Insert: {
          booking_reference: string
          cancellation_reason?: string | null
          cancelled_at?: string | null
          check_in_date: string
          check_out_date: string
          cleaning_fee_amount?: number
          completed_at?: string | null
          confirmed_at?: string | null
          created_at?: string
          currency_code?: string
          discount_amount?: number
          expired_at?: string | null
          guests_count: number
          id?: string
          nightly_amount: number
          owner_actioned_at?: string | null
          owner_id: string
          owner_response_message?: string | null
          payment_reference?: string | null
          payment_status?: Database["public"]["Enums"]["booking_payment_status"]
          payment_submitted_at?: string | null
          property_id: string
          refunded_at?: string | null
          requested_at?: string
          service_fee_amount?: number
          special_requests?: string | null
          status?: Database["public"]["Enums"]["booking_status"]
          subtotal_amount: number
          total_amount: number
          traveler_email?: string | null
          traveler_full_name?: string | null
          traveler_id: string
          traveler_phone?: string | null
          updated_at?: string
        }
        Update: {
          booking_reference?: string
          cancellation_reason?: string | null
          cancelled_at?: string | null
          check_in_date?: string
          check_out_date?: string
          cleaning_fee_amount?: number
          completed_at?: string | null
          confirmed_at?: string | null
          created_at?: string
          currency_code?: string
          discount_amount?: number
          expired_at?: string | null
          guests_count?: number
          id?: string
          nightly_amount?: number
          owner_actioned_at?: string | null
          owner_id?: string
          owner_response_message?: string | null
          payment_reference?: string | null
          payment_status?: Database["public"]["Enums"]["booking_payment_status"]
          payment_submitted_at?: string | null
          property_id?: string
          refunded_at?: string | null
          requested_at?: string
          service_fee_amount?: number
          special_requests?: string | null
          status?: Database["public"]["Enums"]["booking_status"]
          subtotal_amount?: number
          total_amount?: number
          traveler_email?: string | null
          traveler_full_name?: string | null
          traveler_id?: string
          traveler_phone?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "bookings_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_traveler_id_fkey"
            columns: ["traveler_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_members: {
        Row: {
          conversation_id: string
          created_at: string
          id: string
          joined_at: string
          last_read_at: string | null
          last_read_message_id: string | null
          role: Database["public"]["Enums"]["conversation_member_role"]
          updated_at: string
          user_id: string
        }
        Insert: {
          conversation_id: string
          created_at?: string
          id?: string
          joined_at?: string
          last_read_at?: string | null
          last_read_message_id?: string | null
          role: Database["public"]["Enums"]["conversation_member_role"]
          updated_at?: string
          user_id: string
        }
        Update: {
          conversation_id?: string
          created_at?: string
          id?: string
          joined_at?: string
          last_read_at?: string | null
          last_read_message_id?: string | null
          role?: Database["public"]["Enums"]["conversation_member_role"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_members_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_members_last_read_message_id_fkey"
            columns: ["last_read_message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversation_members_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          booking_id: string | null
          conversation_type: Database["public"]["Enums"]["conversation_type"]
          created_at: string
          id: string
          last_message_at: string | null
          property_id: string | null
          subject: string | null
          updated_at: string
        }
        Insert: {
          booking_id?: string | null
          conversation_type?: Database["public"]["Enums"]["conversation_type"]
          created_at?: string
          id?: string
          last_message_at?: string | null
          property_id?: string | null
          subject?: string | null
          updated_at?: string
        }
        Update: {
          booking_id?: string | null
          conversation_type?: Database["public"]["Enums"]["conversation_type"]
          created_at?: string
          id?: string
          last_message_at?: string | null
          property_id?: string | null
          subject?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversations_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "conversations_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          attachment_path: string | null
          body: string | null
          conversation_id: string
          created_at: string
          deleted_at: string | null
          edited_at: string | null
          id: string
          message_type: Database["public"]["Enums"]["message_type"]
          reply_to_message_id: string | null
          sender_id: string | null
          sent_at: string
          updated_at: string
        }
        Insert: {
          attachment_path?: string | null
          body?: string | null
          conversation_id: string
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          message_type?: Database["public"]["Enums"]["message_type"]
          reply_to_message_id?: string | null
          sender_id?: string | null
          sent_at?: string
          updated_at?: string
        }
        Update: {
          attachment_path?: string | null
          body?: string | null
          conversation_id?: string
          created_at?: string
          deleted_at?: string | null
          edited_at?: string | null
          id?: string
          message_type?: Database["public"]["Enums"]["message_type"]
          reply_to_message_id?: string | null
          sender_id?: string | null
          sent_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_reply_to_message_id_fkey"
            columns: ["reply_to_message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          action_url: string | null
          body: string | null
          created_at: string
          deleted_at: string | null
          entity_id: string | null
          entity_type:
            | Database["public"]["Enums"]["notification_entity_type"]
            | null
          id: string
          is_read: boolean
          read_at: string | null
          title: string
          type: Database["public"]["Enums"]["notification_type"]
          updated_at: string
          user_id: string
        }
        Insert: {
          action_url?: string | null
          body?: string | null
          created_at?: string
          deleted_at?: string | null
          entity_id?: string | null
          entity_type?:
            | Database["public"]["Enums"]["notification_entity_type"]
            | null
          id?: string
          is_read?: boolean
          read_at?: string | null
          title: string
          type: Database["public"]["Enums"]["notification_type"]
          updated_at?: string
          user_id: string
        }
        Update: {
          action_url?: string | null
          body?: string | null
          created_at?: string
          deleted_at?: string | null
          entity_id?: string | null
          entity_type?:
            | Database["public"]["Enums"]["notification_entity_type"]
            | null
          id?: string
          is_read?: boolean
          read_at?: string | null
          title?: string
          type?: Database["public"]["Enums"]["notification_type"]
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      owner_verification_documents: {
        Row: {
          created_at: string
          deleted_at: string | null
          document_type: Database["public"]["Enums"]["verification_document_type"]
          file_size_bytes: number
          id: string
          mime_type: string
          original_file_name: string
          owner_verification_id: string
          rejection_reason: string | null
          review_status: Database["public"]["Enums"]["document_review_status"]
          storage_path: string
          updated_at: string
          uploaded_by_profile_id: string
        }
        Insert: {
          created_at?: string
          deleted_at?: string | null
          document_type: Database["public"]["Enums"]["verification_document_type"]
          file_size_bytes: number
          id?: string
          mime_type: string
          original_file_name: string
          owner_verification_id: string
          rejection_reason?: string | null
          review_status?: Database["public"]["Enums"]["document_review_status"]
          storage_path: string
          updated_at?: string
          uploaded_by_profile_id: string
        }
        Update: {
          created_at?: string
          deleted_at?: string | null
          document_type?: Database["public"]["Enums"]["verification_document_type"]
          file_size_bytes?: number
          id?: string
          mime_type?: string
          original_file_name?: string
          owner_verification_id?: string
          rejection_reason?: string | null
          review_status?: Database["public"]["Enums"]["document_review_status"]
          storage_path?: string
          updated_at?: string
          uploaded_by_profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "owner_verification_documents_owner_verification_id_fkey"
            columns: ["owner_verification_id"]
            isOneToOne: false
            referencedRelation: "owner_verifications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "owner_verification_documents_uploaded_by_profile_id_fkey"
            columns: ["uploaded_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      owner_verifications: {
        Row: {
          approved_at: string | null
          business_name: string | null
          business_registration_number: string | null
          created_at: string
          date_of_birth: string | null
          deleted_at: string | null
          id: string
          legal_full_name: string | null
          owner_profile_id: string
          rejected_at: string | null
          rejection_reason_code:
            | Database["public"]["Enums"]["verification_rejection_reason"]
            | null
          review_notes: string | null
          reviewed_by_profile_id: string | null
          status: Database["public"]["Enums"]["verification_status"]
          submitted_at: string | null
          tax_identifier: string | null
          under_review_at: string | null
          updated_at: string
          verification_type: Database["public"]["Enums"]["owner_verification_type"]
        }
        Insert: {
          approved_at?: string | null
          business_name?: string | null
          business_registration_number?: string | null
          created_at?: string
          date_of_birth?: string | null
          deleted_at?: string | null
          id?: string
          legal_full_name?: string | null
          owner_profile_id: string
          rejected_at?: string | null
          rejection_reason_code?:
            | Database["public"]["Enums"]["verification_rejection_reason"]
            | null
          review_notes?: string | null
          reviewed_by_profile_id?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          submitted_at?: string | null
          tax_identifier?: string | null
          under_review_at?: string | null
          updated_at?: string
          verification_type: Database["public"]["Enums"]["owner_verification_type"]
        }
        Update: {
          approved_at?: string | null
          business_name?: string | null
          business_registration_number?: string | null
          created_at?: string
          date_of_birth?: string | null
          deleted_at?: string | null
          id?: string
          legal_full_name?: string | null
          owner_profile_id?: string
          rejected_at?: string | null
          rejection_reason_code?:
            | Database["public"]["Enums"]["verification_rejection_reason"]
            | null
          review_notes?: string | null
          reviewed_by_profile_id?: string | null
          status?: Database["public"]["Enums"]["verification_status"]
          submitted_at?: string | null
          tax_identifier?: string | null
          under_review_at?: string | null
          updated_at?: string
          verification_type?: Database["public"]["Enums"]["owner_verification_type"]
        }
        Relationships: [
          {
            foreignKeyName: "owner_verifications_owner_profile_id_fkey"
            columns: ["owner_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "owner_verifications_reviewed_by_profile_id_fkey"
            columns: ["reviewed_by_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payment_methods: {
        Row: {
          brand: string | null
          created_at: string
          deleted_at: string | null
          display_name: string | null
          expiry_month: number | null
          expiry_year: number | null
          id: string
          is_default: boolean
          last_four: string | null
          method_type: Database["public"]["Enums"]["payment_method_type"]
          provider: Database["public"]["Enums"]["payment_provider"]
          updated_at: string
          user_id: string
          verification_status: Database["public"]["Enums"]["payment_method_verification_status"]
          wallet_identifier: string | null
        }
        Insert: {
          brand?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name?: string | null
          expiry_month?: number | null
          expiry_year?: number | null
          id?: string
          is_default?: boolean
          last_four?: string | null
          method_type: Database["public"]["Enums"]["payment_method_type"]
          provider: Database["public"]["Enums"]["payment_provider"]
          updated_at?: string
          user_id: string
          verification_status?: Database["public"]["Enums"]["payment_method_verification_status"]
          wallet_identifier?: string | null
        }
        Update: {
          brand?: string | null
          created_at?: string
          deleted_at?: string | null
          display_name?: string | null
          expiry_month?: number | null
          expiry_year?: number | null
          id?: string
          is_default?: boolean
          last_four?: string | null
          method_type?: Database["public"]["Enums"]["payment_method_type"]
          provider?: Database["public"]["Enums"]["payment_provider"]
          updated_at?: string
          user_id?: string
          verification_status?: Database["public"]["Enums"]["payment_method_verification_status"]
          wallet_identifier?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payment_methods_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payouts: {
        Row: {
          booking_id: string | null
          cancelled_at: string | null
          commission_amount: number
          created_at: string
          currency_code: string
          external_reference: string | null
          failed_at: string | null
          failure_reason: string | null
          gross_amount: number
          id: string
          method: Database["public"]["Enums"]["payout_method"]
          net_amount: number
          notes: string | null
          owner_id: string
          paid_at: string | null
          processed_at: string | null
          scheduled_for: string | null
          status: Database["public"]["Enums"]["payout_status"]
          updated_at: string
        }
        Insert: {
          booking_id?: string | null
          cancelled_at?: string | null
          commission_amount?: number
          created_at?: string
          currency_code?: string
          external_reference?: string | null
          failed_at?: string | null
          failure_reason?: string | null
          gross_amount: number
          id?: string
          method: Database["public"]["Enums"]["payout_method"]
          net_amount: number
          notes?: string | null
          owner_id: string
          paid_at?: string | null
          processed_at?: string | null
          scheduled_for?: string | null
          status?: Database["public"]["Enums"]["payout_status"]
          updated_at?: string
        }
        Update: {
          booking_id?: string | null
          cancelled_at?: string | null
          commission_amount?: number
          created_at?: string
          currency_code?: string
          external_reference?: string | null
          failed_at?: string | null
          failure_reason?: string | null
          gross_amount?: number
          id?: string
          method?: Database["public"]["Enums"]["payout_method"]
          net_amount?: number
          notes?: string | null
          owner_id?: string
          paid_at?: string | null
          processed_at?: string | null
          scheduled_for?: string | null
          status?: Database["public"]["Enums"]["payout_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "payouts_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: true
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payouts_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          account_type: Database["public"]["Enums"]["account_type"]
          address: string | null
          address_line_1: string | null
          address_line_2: string | null
          avatar_url: string | null
          city: string | null
          country: string | null
          country_code: string | null
          country_name: string | null
          created_at: string
          date_of_birth: string | null
          deactivated_at: string | null
          deleted_at: string | null
          dialing_code: string | null
          display_name: string | null
          email: string
          email_verified: boolean
          email_verified_at: string | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          full_name: string
          id: string
          identity_verified: boolean
          is_active: boolean
          nationality: string | null
          phone: string | null
          phone_verified: boolean
          phone_verified_at: string | null
          preferred_currency: string | null
          preferred_language: string | null
          profile_completion: number
          updated_at: string
        }
        Insert: {
          account_type?: Database["public"]["Enums"]["account_type"]
          address?: string | null
          address_line_1?: string | null
          address_line_2?: string | null
          avatar_url?: string | null
          city?: string | null
          country?: string | null
          country_code?: string | null
          country_name?: string | null
          created_at?: string
          date_of_birth?: string | null
          deactivated_at?: string | null
          deleted_at?: string | null
          dialing_code?: string | null
          display_name?: string | null
          email: string
          email_verified?: boolean
          email_verified_at?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          full_name: string
          id: string
          identity_verified?: boolean
          is_active?: boolean
          nationality?: string | null
          phone?: string | null
          phone_verified?: boolean
          phone_verified_at?: string | null
          preferred_currency?: string | null
          preferred_language?: string | null
          profile_completion?: number
          updated_at?: string
        }
        Update: {
          account_type?: Database["public"]["Enums"]["account_type"]
          address?: string | null
          address_line_1?: string | null
          address_line_2?: string | null
          avatar_url?: string | null
          city?: string | null
          country?: string | null
          country_code?: string | null
          country_name?: string | null
          created_at?: string
          date_of_birth?: string | null
          deactivated_at?: string | null
          deleted_at?: string | null
          dialing_code?: string | null
          display_name?: string | null
          email?: string
          email_verified?: boolean
          email_verified_at?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          full_name?: string
          id?: string
          identity_verified?: boolean
          is_active?: boolean
          nationality?: string | null
          phone?: string | null
          phone_verified?: boolean
          phone_verified_at?: string | null
          preferred_currency?: string | null
          preferred_language?: string | null
          profile_completion?: number
          updated_at?: string
        }
        Relationships: []
      }
      properties: {
        Row: {
          address_line_1: string
          address_line_2: string | null
          approved_at: string | null
          archived_at: string | null
          area: string | null
          area_size_sqm: number | null
          base_nightly_amount: number
          bathrooms_count: number
          bedrooms_count: number
          beds_count: number
          building_name: string | null
          city: string
          cleaning_fee_amount: number
          country_code: string
          country_name: string
          created_at: string
          currency_code: string
          deleted_at: string | null
          description: string | null
          id: string
          instant_book_enabled: boolean
          latitude: number | null
          location_precision: Database["public"]["Enums"]["location_precision"]
          longitude: number | null
          max_guests: number
          maximum_nights: number | null
          minimum_nights: number
          moderation_status: Database["public"]["Enums"]["property_moderation_status"]
          owner_profile_id: string
          property_type: Database["public"]["Enums"]["property_type"]
          public_slug: string
          publication_status: Database["public"]["Enums"]["property_publication_status"]
          published_at: string | null
          rejected_at: string | null
          security_deposit_amount: number
          submitted_for_review_at: string | null
          suspended_at: string | null
          title: string
          unpublished_at: string | null
          updated_at: string
        }
        Insert: {
          address_line_1: string
          address_line_2?: string | null
          approved_at?: string | null
          archived_at?: string | null
          area?: string | null
          area_size_sqm?: number | null
          base_nightly_amount: number
          bathrooms_count?: number
          bedrooms_count?: number
          beds_count?: number
          building_name?: string | null
          city: string
          cleaning_fee_amount?: number
          country_code?: string
          country_name?: string
          created_at?: string
          currency_code?: string
          deleted_at?: string | null
          description?: string | null
          id?: string
          instant_book_enabled?: boolean
          latitude?: number | null
          location_precision?: Database["public"]["Enums"]["location_precision"]
          longitude?: number | null
          max_guests: number
          maximum_nights?: number | null
          minimum_nights?: number
          moderation_status?: Database["public"]["Enums"]["property_moderation_status"]
          owner_profile_id: string
          property_type: Database["public"]["Enums"]["property_type"]
          public_slug: string
          publication_status?: Database["public"]["Enums"]["property_publication_status"]
          published_at?: string | null
          rejected_at?: string | null
          security_deposit_amount?: number
          submitted_for_review_at?: string | null
          suspended_at?: string | null
          title: string
          unpublished_at?: string | null
          updated_at?: string
        }
        Update: {
          address_line_1?: string
          address_line_2?: string | null
          approved_at?: string | null
          archived_at?: string | null
          area?: string | null
          area_size_sqm?: number | null
          base_nightly_amount?: number
          bathrooms_count?: number
          bedrooms_count?: number
          beds_count?: number
          building_name?: string | null
          city?: string
          cleaning_fee_amount?: number
          country_code?: string
          country_name?: string
          created_at?: string
          currency_code?: string
          deleted_at?: string | null
          description?: string | null
          id?: string
          instant_book_enabled?: boolean
          latitude?: number | null
          location_precision?: Database["public"]["Enums"]["location_precision"]
          longitude?: number | null
          max_guests?: number
          maximum_nights?: number | null
          minimum_nights?: number
          moderation_status?: Database["public"]["Enums"]["property_moderation_status"]
          owner_profile_id?: string
          property_type?: Database["public"]["Enums"]["property_type"]
          public_slug?: string
          publication_status?: Database["public"]["Enums"]["property_publication_status"]
          published_at?: string | null
          rejected_at?: string | null
          security_deposit_amount?: number
          submitted_for_review_at?: string | null
          suspended_at?: string | null
          title?: string
          unpublished_at?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "properties_owner_profile_id_fkey"
            columns: ["owner_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      property_availability: {
        Row: {
          availability_date: string
          booking_id: string | null
          created_at: string
          id: string
          note: string | null
          property_id: string
          reason: Database["public"]["Enums"]["availability_reason"] | null
          status: Database["public"]["Enums"]["availability_status"]
          updated_at: string
        }
        Insert: {
          availability_date: string
          booking_id?: string | null
          created_at?: string
          id?: string
          note?: string | null
          property_id: string
          reason?: Database["public"]["Enums"]["availability_reason"] | null
          status?: Database["public"]["Enums"]["availability_status"]
          updated_at?: string
        }
        Update: {
          availability_date?: string
          booking_id?: string | null
          created_at?: string
          id?: string
          note?: string | null
          property_id?: string
          reason?: Database["public"]["Enums"]["availability_reason"] | null
          status?: Database["public"]["Enums"]["availability_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "property_availability_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "property_availability_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_photos: {
        Row: {
          caption: string | null
          created_at: string
          deleted_at: string | null
          height_px: number | null
          id: string
          is_cover: boolean
          photo_category: Database["public"]["Enums"]["property_photo_category"]
          property_id: string
          sort_order: number
          storage_path: string
          updated_at: string
          width_px: number | null
        }
        Insert: {
          caption?: string | null
          created_at?: string
          deleted_at?: string | null
          height_px?: number | null
          id?: string
          is_cover?: boolean
          photo_category?: Database["public"]["Enums"]["property_photo_category"]
          property_id: string
          sort_order: number
          storage_path: string
          updated_at?: string
          width_px?: number | null
        }
        Update: {
          caption?: string | null
          created_at?: string
          deleted_at?: string | null
          height_px?: number | null
          id?: string
          is_cover?: boolean
          photo_category?: Database["public"]["Enums"]["property_photo_category"]
          property_id?: string
          sort_order?: number
          storage_path?: string
          updated_at?: string
          width_px?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "property_photos_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      property_pricing_rules: {
        Row: {
          created_at: string
          days_of_week_mask: number | null
          deleted_at: string | null
          ends_on: string
          id: string
          is_active: boolean
          label: string
          maximum_nights_override: number | null
          minimum_nights_override: number | null
          nightly_amount_override: number | null
          percent_adjustment: number | null
          priority: number
          property_id: string
          rule_type: Database["public"]["Enums"]["pricing_rule_type"]
          starts_on: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          days_of_week_mask?: number | null
          deleted_at?: string | null
          ends_on: string
          id?: string
          is_active?: boolean
          label: string
          maximum_nights_override?: number | null
          minimum_nights_override?: number | null
          nightly_amount_override?: number | null
          percent_adjustment?: number | null
          priority?: number
          property_id: string
          rule_type: Database["public"]["Enums"]["pricing_rule_type"]
          starts_on: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          days_of_week_mask?: number | null
          deleted_at?: string | null
          ends_on?: string
          id?: string
          is_active?: boolean
          label?: string
          maximum_nights_override?: number | null
          minimum_nights_override?: number | null
          nightly_amount_override?: number | null
          percent_adjustment?: number | null
          priority?: number
          property_id?: string
          rule_type?: Database["public"]["Enums"]["pricing_rule_type"]
          starts_on?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "property_pricing_rules_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
        ]
      }
      reviews: {
        Row: {
          accuracy_rating: number | null
          booking_id: string
          cleanliness_rating: number | null
          comment: string | null
          communication_rating: number | null
          created_at: string
          hidden_at: string | null
          id: string
          location_rating: number | null
          owner_id: string
          owner_response: string | null
          property_id: string
          rating: number
          removed_at: string | null
          status: Database["public"]["Enums"]["review_status"]
          submitted_at: string | null
          traveler_id: string
          updated_at: string
          value_rating: number | null
        }
        Insert: {
          accuracy_rating?: number | null
          booking_id: string
          cleanliness_rating?: number | null
          comment?: string | null
          communication_rating?: number | null
          created_at?: string
          hidden_at?: string | null
          id?: string
          location_rating?: number | null
          owner_id: string
          owner_response?: string | null
          property_id: string
          rating: number
          removed_at?: string | null
          status?: Database["public"]["Enums"]["review_status"]
          submitted_at?: string | null
          traveler_id: string
          updated_at?: string
          value_rating?: number | null
        }
        Update: {
          accuracy_rating?: number | null
          booking_id?: string
          cleanliness_rating?: number | null
          comment?: string | null
          communication_rating?: number | null
          created_at?: string
          hidden_at?: string | null
          id?: string
          location_rating?: number | null
          owner_id?: string
          owner_response?: string | null
          property_id?: string
          rating?: number
          removed_at?: string | null
          status?: Database["public"]["Enums"]["review_status"]
          submitted_at?: string | null
          traveler_id?: string
          updated_at?: string
          value_rating?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "reviews_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reviews_traveler_id_fkey"
            columns: ["traveler_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      saved_properties: {
        Row: {
          created_at: string
          id: string
          property_id: string
          traveler_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          property_id: string
          traveler_id: string
        }
        Update: {
          created_at?: string
          id?: string
          property_id?: string
          traveler_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "saved_properties_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "saved_properties_traveler_id_fkey"
            columns: ["traveler_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      support_ticket_messages: {
        Row: {
          created_at: string
          id: string
          is_internal: boolean
          message: string
          sender_id: string | null
          sender_role: Database["public"]["Enums"]["support_sender_role"]
          ticket_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          id?: string
          is_internal?: boolean
          message: string
          sender_id?: string | null
          sender_role?: Database["public"]["Enums"]["support_sender_role"]
          ticket_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          id?: string
          is_internal?: boolean
          message?: string
          sender_id?: string | null
          sender_role?: Database["public"]["Enums"]["support_sender_role"]
          ticket_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_ticket_messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_ticket_messages_ticket_id_fkey"
            columns: ["ticket_id"]
            isOneToOne: false
            referencedRelation: "support_tickets"
            referencedColumns: ["id"]
          },
        ]
      }
      support_tickets: {
        Row: {
          assigned_to_profile_id: string | null
          booking_id: string | null
          category: Database["public"]["Enums"]["support_ticket_category"]
          closed_at: string | null
          created_at: string
          deleted_at: string | null
          id: string
          priority: Database["public"]["Enums"]["support_ticket_priority"]
          property_id: string | null
          resolved_at: string | null
          status: Database["public"]["Enums"]["support_ticket_status"]
          subject: string
          ticket_reference: string
          updated_at: string
          user_id: string
        }
        Insert: {
          assigned_to_profile_id?: string | null
          booking_id?: string | null
          category: Database["public"]["Enums"]["support_ticket_category"]
          closed_at?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          priority?: Database["public"]["Enums"]["support_ticket_priority"]
          property_id?: string | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["support_ticket_status"]
          subject: string
          ticket_reference: string
          updated_at?: string
          user_id: string
        }
        Update: {
          assigned_to_profile_id?: string | null
          booking_id?: string | null
          category?: Database["public"]["Enums"]["support_ticket_category"]
          closed_at?: string | null
          created_at?: string
          deleted_at?: string | null
          id?: string
          priority?: Database["public"]["Enums"]["support_ticket_priority"]
          property_id?: string | null
          resolved_at?: string | null
          status?: Database["public"]["Enums"]["support_ticket_status"]
          subject?: string
          ticket_reference?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "support_tickets_assigned_to_profile_id_fkey"
            columns: ["assigned_to_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_property_id_fkey"
            columns: ["property_id"]
            isOneToOne: false
            referencedRelation: "properties"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "support_tickets_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_support_ticket_message: {
        Args: {
          internal_note?: boolean
          message_input: string
          ticket_uuid: string
        }
        Returns: {
          created_at: string
          is_internal: boolean
          message_id: string
          sender_role: Database["public"]["Enums"]["support_sender_role"]
          status: Database["public"]["Enums"]["support_ticket_status"]
          ticket_id: string
        }[]
      }
      admin_moderate_property: {
        Args: {
          admin_note?: string
          property_uuid: string
          target_status: Database["public"]["Enums"]["property_moderation_status"]
        }
        Returns: {
          approved_at: string
          id: string
          moderation_status: Database["public"]["Enums"]["property_moderation_status"]
          publication_status: Database["public"]["Enums"]["property_publication_status"]
          rejected_at: string
          suspended_at: string
        }[]
      }
      admin_review_owner_verification: {
        Args: {
          rejection_reason_input?: Database["public"]["Enums"]["verification_rejection_reason"]
          review_notes_input?: string
          target_status: Database["public"]["Enums"]["verification_status"]
          verification_uuid: string
        }
        Returns: {
          approved_at: string
          id: string
          owner_profile_id: string
          rejected_at: string
          rejection_reason_code: Database["public"]["Enums"]["verification_rejection_reason"]
          reviewed_by_profile_id: string
          status: Database["public"]["Enums"]["verification_status"]
        }[]
      }
      admin_set_profile_active: {
        Args: { active: boolean; profile_uuid: string }
        Returns: {
          deactivated_at: string
          id: string
          is_active: boolean
        }[]
      }
      can_access_booking: { Args: { booking_uuid: string }; Returns: boolean }
      can_access_support_ticket: {
        Args: { ticket_uuid: string }
        Returns: boolean
      }
      create_or_get_booking_conversation: {
        Args: { booking_uuid: string }
        Returns: {
          booking_id: string
          conversation_id: string
          created_at: string
          property_id: string
          subject: string
          updated_at: string
        }[]
      }
      create_support_ticket: {
        Args: {
          booking_uuid?: string
          category_input: Database["public"]["Enums"]["support_ticket_category"]
          message_input: string
          priority_input?: Database["public"]["Enums"]["support_ticket_priority"]
          subject_input: string
        }
        Returns: {
          booking_id: string
          created_at: string
          property_id: string
          status: Database["public"]["Enums"]["support_ticket_status"]
          ticket_id: string
          ticket_reference: string
        }[]
      }
      create_traveler_booking: {
        Args: {
          payment_method_input?: string
          property_lookup: string
          requested_check_in: string
          requested_check_out: string
          requested_guests: number
          special_requests_input?: string
          traveler_email_input?: string
          traveler_full_name_input?: string
          traveler_phone_input?: string
        }
        Returns: {
          booking_reference: string
          check_in_date: string
          check_out_date: string
          cleaning_fee_amount: number
          currency_code: string
          discount_amount: number
          guests_count: number
          id: string
          nightly_amount: number
          owner_id: string
          payment_reference: string
          payment_status: Database["public"]["Enums"]["booking_payment_status"]
          property_id: string
          service_fee_amount: number
          status: Database["public"]["Enums"]["booking_status"]
          subtotal_amount: number
          total_amount: number
        }[]
      }
      current_account_type: {
        Args: never
        Returns: Database["public"]["Enums"]["account_type"]
      }
      delete_own_conversation_message: {
        Args: { message_uuid: string }
        Returns: {
          conversation_id: string
          deleted_at: string
          message_id: string
        }[]
      }
      delete_owner_property_availability_entry: {
        Args: { availability_uuid: string }
        Returns: {
          id: string
          property_id: string
        }[]
      }
      generate_booking_reference: { Args: never; Returns: string }
      get_conversation_messages: {
        Args: { conversation_uuid: string }
        Returns: {
          attachment_file_name: string
          attachment_path: string
          body: string
          conversation_id: string
          created_at: string
          deleted_at: string
          message_id: string
          message_type: Database["public"]["Enums"]["message_type"]
          reply_to_body: string
          reply_to_message_id: string
          reply_to_sender_name: string
          sender_avatar_url: string
          sender_id: string
          sender_name: string
          sender_role: Database["public"]["Enums"]["conversation_member_role"]
          sent_at: string
          updated_at: string
        }[]
      }
      get_my_conversations: {
        Args: never
        Returns: {
          booking_id: string
          conversation_created_at: string
          conversation_id: string
          conversation_type: Database["public"]["Enums"]["conversation_type"]
          conversation_updated_at: string
          last_message_at: string
          last_message_attachment_file_name: string
          last_message_body: string
          last_message_created_at: string
          last_message_deleted: boolean
          last_message_id: string
          last_message_sender_id: string
          last_message_sender_name: string
          last_message_type: Database["public"]["Enums"]["message_type"]
          last_read_message_id: string
          member_role: Database["public"]["Enums"]["conversation_member_role"]
          participant_avatar_url: string
          participant_id: string
          participant_name: string
          participant_role: Database["public"]["Enums"]["conversation_member_role"]
          participant_verified: boolean
          property_area: string
          property_base_nightly_amount: number
          property_bedrooms_count: number
          property_city: string
          property_country_name: string
          property_id: string
          property_max_guests: number
          property_slug: string
          property_title: string
          property_type: Database["public"]["Enums"]["property_type"]
          subject: string
          unread_count: number
        }[]
      }
      get_owner_booking_details: {
        Args: { booking_uuid: string }
        Returns: {
          booking_reference: string
          cancelled_at: string
          check_in_date: string
          check_out_date: string
          cleaning_fee_amount: number
          completed_at: string
          confirmed_at: string
          created_at: string
          currency_code: string
          discount_amount: number
          guests_count: number
          id: string
          nightly_amount: number
          owner_actioned_at: string
          owner_response_message: string
          payment_reference: string
          payment_status: Database["public"]["Enums"]["booking_payment_status"]
          payment_submitted_at: string
          property_area: string
          property_city: string
          property_country_name: string
          property_id: string
          property_max_guests: number
          property_slug: string
          property_title: string
          property_type: Database["public"]["Enums"]["property_type"]
          requested_at: string
          service_fee_amount: number
          special_requests: string
          status: Database["public"]["Enums"]["booking_status"]
          subtotal_amount: number
          total_amount: number
          traveler_email: string
          traveler_full_name: string
          traveler_id: string
          traveler_phone: string
          updated_at: string
        }[]
      }
      get_owner_bookings: {
        Args: never
        Returns: {
          booking_reference: string
          cancelled_at: string
          check_in_date: string
          check_out_date: string
          cleaning_fee_amount: number
          completed_at: string
          confirmed_at: string
          created_at: string
          currency_code: string
          discount_amount: number
          guests_count: number
          id: string
          nightly_amount: number
          owner_actioned_at: string
          owner_response_message: string
          payment_reference: string
          payment_status: Database["public"]["Enums"]["booking_payment_status"]
          payment_submitted_at: string
          property_area: string
          property_city: string
          property_country_name: string
          property_id: string
          property_max_guests: number
          property_slug: string
          property_title: string
          property_type: Database["public"]["Enums"]["property_type"]
          requested_at: string
          service_fee_amount: number
          special_requests: string
          status: Database["public"]["Enums"]["booking_status"]
          subtotal_amount: number
          total_amount: number
          traveler_email: string
          traveler_full_name: string
          traveler_id: string
          traveler_phone: string
          updated_at: string
        }[]
      }
      get_owner_property: {
        Args: { property_uuid: string }
        Returns: {
          address_line_1: string
          address_line_2: string
          approved_at: string
          archived_at: string
          area: string
          area_size_sqm: number
          base_nightly_amount: number
          bathrooms_count: number
          bedrooms_count: number
          beds_count: number
          building_name: string
          city: string
          cleaning_fee_amount: number
          country_code: string
          country_name: string
          created_at: string
          currency_code: string
          description: string
          id: string
          instant_book_enabled: boolean
          latitude: number
          location_precision: Database["public"]["Enums"]["location_precision"]
          longitude: number
          max_guests: number
          maximum_nights: number
          minimum_nights: number
          moderation_status: Database["public"]["Enums"]["property_moderation_status"]
          owner_profile_id: string
          property_type: Database["public"]["Enums"]["property_type"]
          public_slug: string
          publication_status: Database["public"]["Enums"]["property_publication_status"]
          published_at: string
          rejected_at: string
          security_deposit_amount: number
          submitted_for_review_at: string
          suspended_at: string
          title: string
          unpublished_at: string
          updated_at: string
        }[]
      }
      get_owner_property_availability: {
        Args: { date_from?: string; date_to?: string; property_uuid: string }
        Returns: {
          availability_date: string
          booking_id: string
          id: string
          note: string
          reason: Database["public"]["Enums"]["availability_reason"]
          status: Database["public"]["Enums"]["availability_status"]
        }[]
      }
      get_owner_property_photos: {
        Args: { property_uuid: string }
        Returns: {
          caption: string
          id: string
          is_cover: boolean
          photo_category: Database["public"]["Enums"]["property_photo_category"]
          property_id: string
          sort_order: number
          storage_path: string
        }[]
      }
      get_traveler_booking_details: {
        Args: { booking_uuid: string }
        Returns: {
          booking_reference: string
          cancelled_at: string
          check_in_date: string
          check_out_date: string
          cleaning_fee_amount: number
          completed_at: string
          confirmed_at: string
          created_at: string
          currency_code: string
          discount_amount: number
          guests_count: number
          id: string
          nightly_amount: number
          owner_actioned_at: string
          owner_avatar_url: string
          owner_display_name: string
          owner_full_name: string
          owner_id: string
          owner_response_message: string
          payment_reference: string
          payment_status: Database["public"]["Enums"]["booking_payment_status"]
          payment_submitted_at: string
          property_area: string
          property_area_size_sqm: number
          property_base_nightly_amount: number
          property_bathrooms_count: number
          property_bedrooms_count: number
          property_city: string
          property_country_name: string
          property_id: string
          property_max_guests: number
          property_slug: string
          property_title: string
          property_type: Database["public"]["Enums"]["property_type"]
          requested_at: string
          service_fee_amount: number
          special_requests: string
          status: Database["public"]["Enums"]["booking_status"]
          subtotal_amount: number
          total_amount: number
          traveler_email: string
          traveler_full_name: string
          traveler_phone: string
          updated_at: string
        }[]
      }
      get_traveler_bookings: {
        Args: never
        Returns: {
          booking_reference: string
          cancelled_at: string
          check_in_date: string
          check_out_date: string
          cleaning_fee_amount: number
          completed_at: string
          confirmed_at: string
          created_at: string
          currency_code: string
          discount_amount: number
          guests_count: number
          id: string
          nightly_amount: number
          owner_actioned_at: string
          owner_avatar_url: string
          owner_display_name: string
          owner_full_name: string
          owner_id: string
          owner_response_message: string
          payment_reference: string
          payment_status: Database["public"]["Enums"]["booking_payment_status"]
          payment_submitted_at: string
          property_area: string
          property_area_size_sqm: number
          property_base_nightly_amount: number
          property_bathrooms_count: number
          property_bedrooms_count: number
          property_city: string
          property_country_name: string
          property_id: string
          property_max_guests: number
          property_slug: string
          property_title: string
          property_type: Database["public"]["Enums"]["property_type"]
          requested_at: string
          service_fee_amount: number
          special_requests: string
          status: Database["public"]["Enums"]["booking_status"]
          subtotal_amount: number
          total_amount: number
          traveler_email: string
          traveler_full_name: string
          traveler_phone: string
          updated_at: string
        }[]
      }
      is_admin: { Args: never; Returns: boolean }
      is_conversation_member: {
        Args: { conversation_uuid: string }
        Returns: boolean
      }
      is_property_public: { Args: { property_uuid: string }; Returns: boolean }
      is_staff: { Args: never; Returns: boolean }
      is_support_staff: { Args: never; Returns: boolean }
      list_owner_properties: {
        Args: never
        Returns: {
          area: string
          city: string
          country_name: string
          id: string
          moderation_status: Database["public"]["Enums"]["property_moderation_status"]
          photo_count: number
          publication_status: Database["public"]["Enums"]["property_publication_status"]
          title: string
          updated_at: string
        }[]
      }
      mark_conversation_read: {
        Args: { conversation_uuid: string; last_read_message_uuid?: string }
        Returns: {
          conversation_id: string
          last_read_at: string
          last_read_message_id: string
        }[]
      }
      owner_decide_booking: {
        Args: {
          booking_uuid: string
          owner_decision: string
          response_message?: string
        }
        Returns: {
          booking_reference: string
          confirmed_at: string
          id: string
          owner_actioned_at: string
          owner_response_message: string
          status: Database["public"]["Enums"]["booking_status"]
        }[]
      }
      owns_owner_verification: {
        Args: { verification_uuid: string }
        Returns: boolean
      }
      owns_property: { Args: { property_uuid: string }; Returns: boolean }
      remove_own_review: {
        Args: { review_uuid: string }
        Returns: {
          id: string
          removed_at: string
        }[]
      }
      send_conversation_message: {
        Args: {
          body_input: string
          conversation_uuid: string
          reply_to_message_uuid?: string
        }
        Returns: {
          attachment_file_name: string
          attachment_path: string
          body: string
          conversation_id: string
          created_at: string
          deleted_at: string
          message_id: string
          message_type: Database["public"]["Enums"]["message_type"]
          reply_to_body: string
          reply_to_message_id: string
          reply_to_sender_name: string
          sender_avatar_url: string
          sender_id: string
          sender_name: string
          sender_role: Database["public"]["Enums"]["conversation_member_role"]
          sent_at: string
          updated_at: string
        }[]
      }
      set_owner_property_availability_range: {
        Args: {
          date_from: string
          date_to: string
          property_uuid: string
          target_note?: string
          target_reason?: Database["public"]["Enums"]["availability_reason"]
          target_status: Database["public"]["Enums"]["availability_status"]
        }
        Returns: number
      }
      storage_folder_segment: {
        Args: { object_name: string; segment_index: number }
        Returns: string
      }
      storage_uuid_folder_segment: {
        Args: { object_name: string; segment_index: number }
        Returns: string
      }
      submit_property_for_review: {
        Args: { property_uuid: string }
        Returns: {
          id: string
          moderation_status: Database["public"]["Enums"]["property_moderation_status"]
          publication_status: Database["public"]["Enums"]["property_publication_status"]
          submitted_for_review_at: string
        }[]
      }
      traveler_cancel_booking: {
        Args: { booking_uuid: string; cancellation_note?: string }
        Returns: {
          booking_reference: string
          cancellation_reason: string
          cancelled_at: string
          id: string
          status: Database["public"]["Enums"]["booking_status"]
        }[]
      }
      update_owner_property_availability_entry: {
        Args: {
          availability_uuid: string
          target_note?: string
          target_reason?: Database["public"]["Enums"]["availability_reason"]
          target_status: Database["public"]["Enums"]["availability_status"]
        }
        Returns: {
          availability_date: string
          id: string
          note: string
          property_id: string
          reason: Database["public"]["Enums"]["availability_reason"]
          status: Database["public"]["Enums"]["availability_status"]
        }[]
      }
      uuid_or_null: { Args: { input_text: string }; Returns: string }
    }
    Enums: {
      account_type: "guest" | "owner" | "admin" | "support_staff"
      audit_action_type:
        | "created"
        | "updated"
        | "submitted"
        | "approved"
        | "rejected"
        | "published"
        | "unpublished"
        | "suspended"
        | "cancelled"
        | "resolved"
        | "processed"
        | "deleted"
      audit_actor_type: "profile" | "system"
      audit_entity_type:
        | "profile"
        | "owner_verification"
        | "property"
        | "booking"
        | "conversation"
        | "message"
        | "review"
        | "payment_method"
        | "payout"
        | "support_ticket"
      availability_reason:
        | "owner_blocked"
        | "maintenance"
        | "booking_hold"
        | "confirmed_booking"
        | "system_rule"
      availability_status: "available" | "blocked" | "booked"
      booking_payment_status:
        | "pending"
        | "under_review"
        | "authorized"
        | "paid"
        | "failed"
        | "refunded"
        | "partially_refunded"
      booking_status:
        | "pending_payment_verification"
        | "pending_owner_approval"
        | "confirmed"
        | "declined"
        | "cancelled"
        | "completed"
        | "expired"
        | "refunded"
      conversation_member_role: "traveler" | "owner" | "system"
      conversation_type: "traveler_owner" | "system"
      document_review_status:
        | "pending"
        | "approved"
        | "rejected"
        | "needs_resubmission"
      location_precision: "approximate" | "exact_private" | "exact_public"
      message_type: "text" | "image" | "file" | "system"
      notification_entity_type:
        | "booking"
        | "property"
        | "conversation"
        | "message"
        | "support_ticket"
        | "review"
        | "payout"
        | "verification"
      notification_type:
        | "booking"
        | "payment"
        | "approval"
        | "message"
        | "support"
        | "review"
        | "system"
        | "payout"
      owner_verification_type: "individual" | "business"
      payment_method_type:
        | "card"
        | "wallet"
        | "bank_transfer"
        | "cash_collection"
        | "pay_on_arrival"
      payment_method_verification_status:
        | "unverified"
        | "pending"
        | "verified"
        | "failed"
      payment_provider:
        | "visa"
        | "mastercard"
        | "meeza"
        | "instapay"
        | "vodafone_cash"
        | "fawry"
        | "bank"
        | "paymob"
        | "cash"
      payout_method:
        | "bank_transfer"
        | "instapay"
        | "vodafone_cash"
        | "cash_pickup"
      payout_status:
        | "pending"
        | "scheduled"
        | "processing"
        | "paid"
        | "failed"
        | "on_hold"
        | "cancelled"
      pricing_rule_type:
        | "seasonal_override"
        | "weekend_override"
        | "date_range_discount"
        | "date_range_markup"
        | "minimum_stay_override"
        | "custom"
      property_moderation_status:
        | "draft"
        | "submitted"
        | "under_review"
        | "approved"
        | "rejected"
        | "suspended"
      property_photo_category:
        | "cover"
        | "living_room"
        | "bedroom"
        | "bathroom"
        | "kitchen"
        | "balcony"
        | "exterior"
        | "amenity"
        | "other"
      property_publication_status: "unpublished" | "published" | "archived"
      property_type: "apartment" | "studio" | "villa" | "duplex" | "hotel"
      review_status: "pending" | "submitted" | "hidden" | "removed"
      support_sender_role: "traveler" | "owner" | "support_staff" | "system"
      support_ticket_category:
        | "payment_issue"
        | "booking_issue"
        | "refund_request"
        | "property_issue"
        | "account_issue"
        | "verification_issue"
        | "technical_issue"
        | "other"
      support_ticket_priority: "low" | "medium" | "high" | "urgent"
      support_ticket_status:
        | "open"
        | "awaiting_customer"
        | "awaiting_support"
        | "in_progress"
        | "resolved"
        | "closed"
        | "escalated"
      verification_document_type:
        | "national_id_front"
        | "national_id_back"
        | "passport"
        | "selfie"
        | "property_deed"
        | "rental_authorization"
        | "utility_bill"
        | "business_registration"
        | "tax_document"
        | "other"
      verification_rejection_reason:
        | "document_missing"
        | "document_unreadable"
        | "name_mismatch"
        | "address_mismatch"
        | "business_record_invalid"
        | "tax_record_invalid"
        | "duplicate_submission"
        | "manual_review_required"
        | "other"
      verification_status:
        | "not_started"
        | "draft"
        | "submitted"
        | "under_review"
        | "approved"
        | "rejected"
        | "expired"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      account_type: ["guest", "owner", "admin", "support_staff"],
      audit_action_type: [
        "created",
        "updated",
        "submitted",
        "approved",
        "rejected",
        "published",
        "unpublished",
        "suspended",
        "cancelled",
        "resolved",
        "processed",
        "deleted",
      ],
      audit_actor_type: ["profile", "system"],
      audit_entity_type: [
        "profile",
        "owner_verification",
        "property",
        "booking",
        "conversation",
        "message",
        "review",
        "payment_method",
        "payout",
        "support_ticket",
      ],
      availability_reason: [
        "owner_blocked",
        "maintenance",
        "booking_hold",
        "confirmed_booking",
        "system_rule",
      ],
      availability_status: ["available", "blocked", "booked"],
      booking_payment_status: [
        "pending",
        "under_review",
        "authorized",
        "paid",
        "failed",
        "refunded",
        "partially_refunded",
      ],
      booking_status: [
        "pending_payment_verification",
        "pending_owner_approval",
        "confirmed",
        "declined",
        "cancelled",
        "completed",
        "expired",
        "refunded",
      ],
      conversation_member_role: ["traveler", "owner", "system"],
      conversation_type: ["traveler_owner", "system"],
      document_review_status: [
        "pending",
        "approved",
        "rejected",
        "needs_resubmission",
      ],
      location_precision: ["approximate", "exact_private", "exact_public"],
      message_type: ["text", "image", "file", "system"],
      notification_entity_type: [
        "booking",
        "property",
        "conversation",
        "message",
        "support_ticket",
        "review",
        "payout",
        "verification",
      ],
      notification_type: [
        "booking",
        "payment",
        "approval",
        "message",
        "support",
        "review",
        "system",
        "payout",
      ],
      owner_verification_type: ["individual", "business"],
      payment_method_type: [
        "card",
        "wallet",
        "bank_transfer",
        "cash_collection",
        "pay_on_arrival",
      ],
      payment_method_verification_status: [
        "unverified",
        "pending",
        "verified",
        "failed",
      ],
      payment_provider: [
        "visa",
        "mastercard",
        "meeza",
        "instapay",
        "vodafone_cash",
        "fawry",
        "bank",
        "paymob",
        "cash",
      ],
      payout_method: [
        "bank_transfer",
        "instapay",
        "vodafone_cash",
        "cash_pickup",
      ],
      payout_status: [
        "pending",
        "scheduled",
        "processing",
        "paid",
        "failed",
        "on_hold",
        "cancelled",
      ],
      pricing_rule_type: [
        "seasonal_override",
        "weekend_override",
        "date_range_discount",
        "date_range_markup",
        "minimum_stay_override",
        "custom",
      ],
      property_moderation_status: [
        "draft",
        "submitted",
        "under_review",
        "approved",
        "rejected",
        "suspended",
      ],
      property_photo_category: [
        "cover",
        "living_room",
        "bedroom",
        "bathroom",
        "kitchen",
        "balcony",
        "exterior",
        "amenity",
        "other",
      ],
      property_publication_status: ["unpublished", "published", "archived"],
      property_type: ["apartment", "studio", "villa", "duplex", "hotel"],
      review_status: ["pending", "submitted", "hidden", "removed"],
      support_sender_role: ["traveler", "owner", "support_staff", "system"],
      support_ticket_category: [
        "payment_issue",
        "booking_issue",
        "refund_request",
        "property_issue",
        "account_issue",
        "verification_issue",
        "technical_issue",
        "other",
      ],
      support_ticket_priority: ["low", "medium", "high", "urgent"],
      support_ticket_status: [
        "open",
        "awaiting_customer",
        "awaiting_support",
        "in_progress",
        "resolved",
        "closed",
        "escalated",
      ],
      verification_document_type: [
        "national_id_front",
        "national_id_back",
        "passport",
        "selfie",
        "property_deed",
        "rental_authorization",
        "utility_bill",
        "business_registration",
        "tax_document",
        "other",
      ],
      verification_rejection_reason: [
        "document_missing",
        "document_unreadable",
        "name_mismatch",
        "address_mismatch",
        "business_record_invalid",
        "tax_record_invalid",
        "duplicate_submission",
        "manual_review_required",
        "other",
      ],
      verification_status: [
        "not_started",
        "draft",
        "submitted",
        "under_review",
        "approved",
        "rejected",
        "expired",
      ],
    },
  },
} as const

